import type { StatGlossaryEntry, StatSport } from "@/lib/stats/types";

const MLB_STATS = [
  {
    key: "ERA",
    sport: "MLB",
    displayName: "ERA",
    aliases: ["earned run average"],
    shortDescription: "Runs a pitcher allows per nine innings, excluding unearned runs.",
    plainEnglishExplanation: "ERA is the quick scoreboard stat for run prevention. It tells you how many earned runs a pitcher would allow over a full nine-inning game.",
    formulaText: "(Earned Runs / Innings Pitched) x 9",
    formulaParts: [
      { label: "Earned Runs", value: "Runs charged to the pitcher that were not caused by fielding errors." },
      { label: "Innings Pitched", value: "Outs recorded, converted into innings." },
      { label: "Times 9", value: "Scales the rate to a full game." },
    ],
    betterDirection: "lower",
    thresholds: [
      { label: "Ace level", rangeLabel: "Below 3.00", interpretation: "Dominant run prevention.", tone: "elite" },
      { label: "Strong", rangeLabel: "3.00 to 3.75", interpretation: "Above-average starter quality.", tone: "good" },
      { label: "Average", rangeLabel: "3.75 to 4.40", interpretation: "Around league norm.", tone: "average" },
      { label: "Risk zone", rangeLabel: "Above 4.40", interpretation: "Allowing too many earned runs.", tone: "warning" },
    ],
    leagueAverageLabel: "League average is usually around 4.00 to 4.30.",
    impactTags: ["Run prevention", "Starting pitching", "Bullpen evaluation"],
    advancedNote: "ERA depends on defense, sequencing, park effects, and official scoring. Use FIP and WHIP with it.",
  },
  {
    key: "WHIP",
    sport: "MLB",
    displayName: "WHIP",
    aliases: ["walks and hits per inning pitched"],
    shortDescription: "How many baserunners a pitcher allows per inning.",
    plainEnglishExplanation: "WHIP answers a simple question: how much traffic does a pitcher allow? Lower WHIP usually means fewer jams and fewer scoring chances for opponents.",
    formulaText: "(Walks + Hits) / Innings Pitched",
    formulaParts: [
      { label: "Walks", value: "Bases on balls allowed." },
      { label: "Hits", value: "Hits allowed by the pitcher." },
      { label: "Innings Pitched", value: "Used to turn total traffic into a rate stat." },
    ],
    betterDirection: "lower",
    thresholds: [
      { label: "Elite", rangeLabel: "Below 1.05", interpretation: "Very few baserunners allowed.", tone: "elite" },
      { label: "Strong", rangeLabel: "1.05 to 1.20", interpretation: "Consistently efficient.", tone: "good" },
      { label: "Average", rangeLabel: "1.20 to 1.32", interpretation: "Near league norm.", tone: "average" },
      { label: "Traffic-heavy", rangeLabel: "Above 1.32", interpretation: "Too many runners reaching base.", tone: "warning" },
    ],
    leagueAverageLabel: "League average is usually around 1.28 to 1.32.",
    impactTags: ["Traffic control", "Pitching efficiency", "Run prevention"],
    advancedNote: "WHIP ignores hit quality and sequencing, so it is best as a fast baserunner snapshot, not a full pitching model.",
  },
  {
    key: "AVG",
    sport: "MLB",
    displayName: "AVG",
    aliases: ["batting average"],
    shortDescription: "How often a hitter gets a hit per at-bat.",
    plainEnglishExplanation: "AVG is the classic contact stat. It tells you how often a hitter turns an at-bat into a hit, but it does not reward walks or extra-base power.",
    formulaText: "Hits / At-Bats",
    formulaParts: [
      { label: "Hits", value: "Singles, doubles, triples, and home runs." },
      { label: "At-Bats", value: "Plate appearances that count as official at-bats." },
    ],
    betterDirection: "higher",
    thresholds: [
      { label: "Excellent", rangeLabel: ".300+", interpretation: "High-end contact production.", tone: "elite" },
      { label: "Good", rangeLabel: ".270 to .299", interpretation: "Above-average hitter.", tone: "good" },
      { label: "Average", rangeLabel: ".240 to .269", interpretation: "Around league norm.", tone: "average" },
      { label: "Low", rangeLabel: "Below .240", interpretation: "Contact results are lagging.", tone: "warning" },
    ],
    leagueAverageLabel: "League average usually sits around .245 to .250.",
    impactTags: ["Contact", "Hitting", "Bat-to-ball skill"],
    advancedNote: "AVG hides walks and power. OBP and SLG usually give a fuller offensive picture.",
  },
  {
    key: "OBP",
    sport: "MLB",
    displayName: "OBP",
    aliases: ["on-base percentage"],
    shortDescription: "How often a hitter reaches base.",
    plainEnglishExplanation: "OBP values not just hits, but also walks and hit-by-pitches. It is one of the best quick stats for how often a hitter creates opportunities.",
    formulaText: "(Hits + Walks + Hit By Pitch) / (At-Bats + Walks + Hit By Pitch + Sacrifice Flies)",
    formulaParts: [
      { label: "Ways on base", value: "Hits, walks, and hit-by-pitches count." },
      { label: "Opportunities", value: "Plate appearances that meaningfully test getting on base." },
    ],
    betterDirection: "higher",
    thresholds: [
      { label: "Elite", rangeLabel: ".380+", interpretation: "Constantly setting the table.", tone: "elite" },
      { label: "Strong", rangeLabel: ".340 to .379", interpretation: "Above-average on-base skill.", tone: "good" },
      { label: "Average", rangeLabel: ".310 to .339", interpretation: "Near league norm.", tone: "average" },
      { label: "Low", rangeLabel: "Below .310", interpretation: "Not enough runners created.", tone: "warning" },
    ],
    leagueAverageLabel: "League average is often near .315 to .320.",
    impactTags: ["Table setting", "Plate discipline", "Run creation"],
    advancedNote: "OBP treats every time on base similarly, so pair it with SLG or OPS to capture damage as well as access.",
  },
  {
    key: "SLG",
    sport: "MLB",
    displayName: "SLG",
    aliases: ["slugging", "slugging percentage"],
    shortDescription: "How many total bases a hitter averages per at-bat.",
    plainEnglishExplanation: "SLG is a quick power meter. It rewards doubles, triples, and home runs more than singles because extra-base hits create more value.",
    formulaText: "Total Bases / At-Bats",
    formulaParts: [
      { label: "Total Bases", value: "Singles count as 1, doubles 2, triples 3, home runs 4." },
      { label: "At-Bats", value: "The hitter's official at-bats." },
    ],
    betterDirection: "higher",
    thresholds: [
      { label: "Impact power", rangeLabel: ".500+", interpretation: "Big extra-base damage.", tone: "elite" },
      { label: "Good", rangeLabel: ".430 to .499", interpretation: "Above-average power output.", tone: "good" },
      { label: "Average", rangeLabel: ".390 to .429", interpretation: "Around league norm.", tone: "average" },
      { label: "Light power", rangeLabel: "Below .390", interpretation: "Limited extra-base impact.", tone: "warning" },
    ],
    leagueAverageLabel: "League average is usually around .400 to .410.",
    impactTags: ["Power", "Extra-base hits", "Run production"],
    advancedNote: "SLG does not include walks, so it should not stand alone when judging full offensive value.",
  },
  {
    key: "OPS",
    sport: "MLB",
    displayName: "OPS",
    aliases: ["on-base plus slugging"],
    shortDescription: "A hitter's on-base skill plus power in one number.",
    plainEnglishExplanation: "OPS combines getting on base and hitting for power. It is popular because it is easy to read and usually tracks overall offensive value reasonably well.",
    formulaText: "OBP + SLG",
    formulaParts: [
      { label: "OBP", value: "How often the hitter reaches base." },
      { label: "SLG", value: "How much power the hitter produces." },
    ],
    betterDirection: "higher",
    thresholds: [
      { label: "Star level", rangeLabel: ".900+", interpretation: "High-end offensive force.", tone: "elite" },
      { label: "Strong", rangeLabel: ".760 to .899", interpretation: "Well above average.", tone: "good" },
      { label: "Average", rangeLabel: ".700 to .759", interpretation: "Around league norm.", tone: "average" },
      { label: "Below average", rangeLabel: "Below .700", interpretation: "Limited overall production.", tone: "warning" },
    ],
    leagueAverageLabel: "League average is usually around .710 to .730.",
    impactTags: ["Offense", "On-base skill", "Power blend"],
    advancedNote: "OPS is useful, but it does not weight OBP and SLG perfectly. More advanced models like wOBA do that better.",
  },
  {
    key: "WAR",
    sport: "MLB",
    displayName: "WAR",
    aliases: ["wins above replacement"],
    shortDescription: "Estimated total value versus a replacement-level player.",
    plainEnglishExplanation: "WAR tries to answer one big question: how many wins did this player add compared with a cheap, readily available backup? It blends offense, defense, base running, or pitching into one value estimate.",
    formulaText: "Comprehensive model combining batting, pitching, fielding, base running, playing time, and replacement level adjustments",
    formulaParts: [
      { label: "Production", value: "Offense or pitching performance creates the value base." },
      { label: "Context adjustments", value: "Position, park, era, and playing time are folded in." },
      { label: "Replacement level", value: "Measures value above a low-cost roster fill-in." },
    ],
    betterDirection: "higher",
    thresholds: [
      { label: "MVP/Cy Young tier", rangeLabel: "6.0+", interpretation: "Elite season impact.", tone: "elite" },
      { label: "All-Star level", rangeLabel: "3.0 to 5.9", interpretation: "Strong everyday or frontline value.", tone: "good" },
      { label: "Solid regular", rangeLabel: "1.5 to 2.9", interpretation: "Useful positive contributor.", tone: "average" },
      { label: "Limited value", rangeLabel: "Below 1.5", interpretation: "Near replacement or worse.", tone: "warning" },
    ],
    leagueAverageLabel: "A typical regular often lands near 2 WAR over a full season.",
    impactTags: ["All-around value", "Roster building", "Awards context"],
    advancedNote: "WAR is model-based and differs by source. Use it as a strong summary, not a precise single truth.",
  },
  {
    key: "K/9",
    sport: "MLB",
    displayName: "K/9",
    aliases: ["strikeouts per nine", "strikeouts per 9"],
    shortDescription: "Strikeouts a pitcher records every nine innings.",
    plainEnglishExplanation: "K/9 shows how much swing-and-miss a pitcher generates. Higher numbers usually mean the pitcher can end at-bats without needing the defense.",
    formulaText: "(Strikeouts / Innings Pitched) x 9",
    formulaParts: [
      { label: "Strikeouts", value: "Total batters retired via strikeout." },
      { label: "Innings Pitched", value: "Used to turn strikeouts into a rate stat." },
      { label: "Times 9", value: "Scales it to a full game." },
    ],
    betterDirection: "higher",
    thresholds: [
      { label: "Bat-missing", rangeLabel: "10.0+", interpretation: "Premium strikeout stuff.", tone: "elite" },
      { label: "Strong", rangeLabel: "8.5 to 9.9", interpretation: "Above-average strikeout rate.", tone: "good" },
      { label: "Average", rangeLabel: "7.5 to 8.4", interpretation: "Normal swing-and-miss profile.", tone: "average" },
      { label: "Contact-heavy", rangeLabel: "Below 7.5", interpretation: "More balls in play to manage.", tone: "warning" },
    ],
    leagueAverageLabel: "League average is often near 8.5 K/9.",
    impactTags: ["Swing-and-miss", "Pitcher dominance", "DFS upside"],
    advancedNote: "K/9 is clean and easy, but strikeout percentage is even better because it removes inning and contact noise.",
  },
  {
    key: "BB/9",
    sport: "MLB",
    displayName: "BB/9",
    aliases: ["walks per nine", "walks per 9"],
    shortDescription: "Walks a pitcher allows every nine innings.",
    plainEnglishExplanation: "BB/9 measures control. Lower is better because free passes create baserunners without forcing the hitter to earn them.",
    formulaText: "(Walks / Innings Pitched) x 9",
    formulaParts: [
      { label: "Walks", value: "Bases on balls issued by the pitcher." },
      { label: "Innings Pitched", value: "Turns walks into a rate." },
      { label: "Times 9", value: "Scales to a full game." },
    ],
    betterDirection: "lower",
    thresholds: [
      { label: "Pinpoint", rangeLabel: "Below 2.0", interpretation: "Excellent command.", tone: "elite" },
      { label: "Good", rangeLabel: "2.0 to 2.8", interpretation: "Strong control.", tone: "good" },
      { label: "Average", rangeLabel: "2.9 to 3.5", interpretation: "Manageable walk rate.", tone: "average" },
      { label: "Wild", rangeLabel: "Above 3.5", interpretation: "Too many free baserunners.", tone: "warning" },
    ],
    leagueAverageLabel: "League average is usually around 3.0 BB/9.",
    impactTags: ["Control", "Pitch efficiency", "Baserunner management"],
    advancedNote: "BB/9 is useful, but walk percentage is more precise because it measures against batters faced.",
  },
  {
    key: "FIP",
    sport: "MLB",
    displayName: "FIP",
    aliases: ["fielding independent pitching"],
    shortDescription: "Pitching value based mostly on strikeouts, walks, hit batters, and home runs.",
    plainEnglishExplanation: "FIP tries to isolate what the pitcher most directly controls. It strips away a lot of defensive noise and focuses on the outcomes least influenced by fielders.",
    formulaText: "((13 x HR) + (3 x (BB + HBP)) - (2 x K)) / IP + constant",
    formulaParts: [
      { label: "Home Runs", value: "Heavily penalized because they end the play with damage." },
      { label: "Walks and HBP", value: "Add traffic without balls in play." },
      { label: "Strikeouts", value: "Reward outcomes the defense cannot affect." },
      { label: "Constant", value: "Keeps FIP on an ERA-like scale." },
    ],
    betterDirection: "lower",
    thresholds: [
      { label: "Elite", rangeLabel: "Below 3.20", interpretation: "Excellent pitcher-controlled profile.", tone: "elite" },
      { label: "Strong", rangeLabel: "3.20 to 3.80", interpretation: "Above-average underlying run prevention.", tone: "good" },
      { label: "Average", rangeLabel: "3.80 to 4.20", interpretation: "Near league norm.", tone: "average" },
      { label: "Risk zone", rangeLabel: "Above 4.20", interpretation: "Underlying indicators are shaky.", tone: "warning" },
    ],
    leagueAverageLabel: "League average usually lands near 4.00.",
    impactTags: ["Underlying pitching", "Defense-independent view", "Projection help"],
    advancedNote: "FIP ignores batted-ball profile and contact management, so some pitchers consistently beat or trail it.",
  },
  {
    key: "BABIP",
    sport: "MLB",
    displayName: "BABIP",
    aliases: ["batting average on balls in play"],
    shortDescription: "How often balls in play fall in for hits.",
    plainEnglishExplanation: "BABIP is often used to spot luck, contact quality, or defensive help. It removes strikeouts and home runs so you can focus on what happened when the ball stayed in play.",
    formulaText: "(Hits - Home Runs) / (At-Bats - Strikeouts - Home Runs + Sacrifice Flies)",
    formulaParts: [
      { label: "Hits in play", value: "Hits that happened on balls fielders had a chance to convert." },
      { label: "Balls in play", value: "At-bats minus strikeouts and home runs, plus sacrifice flies." },
    ],
    betterDirection: "contextual",
    thresholds: [
      { label: "Very high", rangeLabel: ".340+", interpretation: "Could reflect hard contact, speed, or favorable variance.", tone: "elite" },
      { label: "Healthy", rangeLabel: ".300 to .339", interpretation: "Often normal to good results.", tone: "good" },
      { label: "Typical", rangeLabel: ".280 to .299", interpretation: "Common baseline range.", tone: "average" },
      { label: "Very low", rangeLabel: "Below .280", interpretation: "Could signal weak contact or poor luck.", tone: "warning" },
    ],
    leagueAverageLabel: "League average is usually near .290 to .300.",
    impactTags: ["Luck signals", "Contact quality", "Regression watch"],
    advancedNote: "BABIP is highly context-sensitive. Fast runners and hard-contact hitters can sustain higher marks than average.",
  },
  {
    key: "ISO",
    sport: "MLB",
    displayName: "ISO",
    aliases: ["isolated power"],
    shortDescription: "Extra-base hit power separated from batting average.",
    plainEnglishExplanation: "ISO measures raw power by asking how much slugging sits on top of simple hit rate. It strips out singles-heavy batting average and isolates damage.",
    formulaText: "SLG - AVG",
    formulaParts: [
      { label: "SLG", value: "Captures all total bases per at-bat." },
      { label: "AVG", value: "Removes the single-hit baseline." },
    ],
    betterDirection: "higher",
    thresholds: [
      { label: "Big power", rangeLabel: ".250+", interpretation: "Serious extra-base threat.", tone: "elite" },
      { label: "Good", rangeLabel: ".180 to .249", interpretation: "Above-average power.", tone: "good" },
      { label: "Average", rangeLabel: ".140 to .179", interpretation: "Normal pop.", tone: "average" },
      { label: "Light", rangeLabel: "Below .140", interpretation: "Limited damage output.", tone: "warning" },
    ],
    leagueAverageLabel: "League average is often around .160 to .170.",
    impactTags: ["Power", "Extra-base impact", "Slugging support"],
    advancedNote: "ISO is excellent for pure power, but it does not tell you whether the hitter also reaches base consistently.",
  },
] as const satisfies readonly StatGlossaryEntry[];

const NBA_STATS = [
  {
    key: "PPG",
    sport: "NBA",
    displayName: "PPG",
    aliases: ["points per game"],
    shortDescription: "Average points scored per game.",
    plainEnglishExplanation: "PPG is the fastest snapshot of a scorer's raw scoring volume. It tells you how many points a player typically produces on the scoreboard each night.",
    formulaText: "Points / Games Played",
    formulaParts: [
      { label: "Points", value: "Total points scored." },
      { label: "Games Played", value: "Turns total scoring into a nightly average." },
    ],
    betterDirection: "higher",
    thresholds: [
      { label: "Elite scorer", rangeLabel: "28+", interpretation: "Primary star-level scorer.", tone: "elite" },
      { label: "Strong", rangeLabel: "20 to 27.9", interpretation: "Clear offensive driver.", tone: "good" },
      { label: "Average", rangeLabel: "12 to 19.9", interpretation: "Useful scoring contribution.", tone: "average" },
      { label: "Low volume", rangeLabel: "Below 12", interpretation: "Limited scoring load.", tone: "warning" },
    ],
    leagueAverageLabel: "Most rotation players land well below 20 PPG.",
    impactTags: ["Scoring volume", "Role size", "Offensive load"],
    advancedNote: "PPG says nothing about efficiency. Pair it with TS% or shot quality context.",
  },
  {
    key: "RPG",
    sport: "NBA",
    displayName: "RPG",
    aliases: ["rebounds per game"],
    shortDescription: "Average rebounds collected per game.",
    plainEnglishExplanation: "RPG measures rebounding volume. It helps show who ends possessions on defense or extends them on offense.",
    formulaText: "Rebounds / Games Played",
    formulaParts: [
      { label: "Rebounds", value: "Offensive plus defensive boards." },
      { label: "Games Played", value: "Turns total rebounding into a nightly average." },
    ],
    betterDirection: "higher",
    thresholds: [
      { label: "Board force", rangeLabel: "11+", interpretation: "Controls the glass.", tone: "elite" },
      { label: "Strong", rangeLabel: "8 to 10.9", interpretation: "Above-average rebounder.", tone: "good" },
      { label: "Average", rangeLabel: "5 to 7.9", interpretation: "Solid mixed-position rebounding.", tone: "average" },
      { label: "Low", rangeLabel: "Below 5", interpretation: "Limited rebound volume.", tone: "warning" },
    ],
    leagueAverageLabel: "Rebounding averages depend heavily on position and minutes.",
    impactTags: ["Possession control", "Frontcourt value", "Second-chance prevention"],
  },
  {
    key: "APG",
    sport: "NBA",
    displayName: "APG",
    aliases: ["assists per game"],
    shortDescription: "Average assists created per game.",
    plainEnglishExplanation: "APG tracks how often a player directly creates made baskets for teammates. It is a quick read on playmaking role and passing volume.",
    formulaText: "Assists / Games Played",
    formulaParts: [
      { label: "Assists", value: "Passes that directly lead to made field goals." },
      { label: "Games Played", value: "Turns total playmaking into a game average." },
    ],
    betterDirection: "higher",
    thresholds: [
      { label: "Lead creator", rangeLabel: "8+", interpretation: "Primary offense organizer.", tone: "elite" },
      { label: "Strong", rangeLabel: "5 to 7.9", interpretation: "Reliable table setter.", tone: "good" },
      { label: "Average", rangeLabel: "3 to 4.9", interpretation: "Useful secondary playmaking.", tone: "average" },
      { label: "Low", rangeLabel: "Below 3", interpretation: "Limited passing load.", tone: "warning" },
    ],
    leagueAverageLabel: "Assist averages depend strongly on position, role, and minutes.",
    impactTags: ["Playmaking", "Ball movement", "Offense creation"],
    advancedNote: "APG depends on teammates finishing shots. Assist rate is usually a cleaner playmaking stat.",
  },
  {
    key: "FG%",
    sport: "NBA",
    displayName: "FG%",
    aliases: ["field goal percentage"],
    shortDescription: "Share of field-goal attempts that go in.",
    plainEnglishExplanation: "FG% is the classic shooting stat. It tells you how often a player makes shots from the field, but it treats twos and threes the same.",
    formulaText: "Field Goals Made / Field Goals Attempted",
    formulaParts: [
      { label: "Makes", value: "All made two-point and three-point field goals." },
      { label: "Attempts", value: "All shots taken from the field." },
    ],
    betterDirection: "higher",
    thresholds: [
      { label: "Excellent", rangeLabel: "52%+", interpretation: "Very efficient raw conversion.", tone: "elite" },
      { label: "Good", rangeLabel: "47% to 51.9%", interpretation: "Above-average accuracy.", tone: "good" },
      { label: "Average", rangeLabel: "44% to 46.9%", interpretation: "Around league norm.", tone: "average" },
      { label: "Low", rangeLabel: "Below 44%", interpretation: "Inefficient raw shooting.", tone: "warning" },
    ],
    leagueAverageLabel: "League average is usually around 47%.",
    impactTags: ["Shot making", "Basic efficiency", "Scoring"],
    advancedNote: "FG% undervalues three-pointers and free throws. TS% is usually the better efficiency stat.",
  },
  {
    key: "3P%",
    sport: "NBA",
    displayName: "3P%",
    aliases: ["three point percentage", "3pt%"],
    shortDescription: "Share of three-point attempts that go in.",
    plainEnglishExplanation: "3P% measures long-range accuracy. It helps show whether a player or team can reliably stretch the floor.",
    formulaText: "Three-Point Field Goals Made / Three-Point Field Goals Attempted",
    formulaParts: [
      { label: "3PM", value: "Made threes." },
      { label: "3PA", value: "Three-point attempts." },
    ],
    betterDirection: "higher",
    thresholds: [
      { label: "Sniper", rangeLabel: "40%+", interpretation: "High-end spacing threat.", tone: "elite" },
      { label: "Good", rangeLabel: "36% to 39.9%", interpretation: "Strong floor spacing.", tone: "good" },
      { label: "Average", rangeLabel: "34% to 35.9%", interpretation: "League-normal accuracy.", tone: "average" },
      { label: "Below average", rangeLabel: "Below 34%", interpretation: "Outside shooting is shaky.", tone: "warning" },
    ],
    leagueAverageLabel: "League average is usually around 35% to 36%.",
    impactTags: ["Spacing", "Perimeter shooting", "Lineup fit"],
  },
  {
    key: "FT%",
    sport: "NBA",
    displayName: "FT%",
    aliases: ["free throw percentage"],
    shortDescription: "Share of free throws made.",
    plainEnglishExplanation: "FT% shows how efficient a player is at the line. It matters in close games and often tracks touch that can carry into shooting skill.",
    formulaText: "Free Throws Made / Free Throws Attempted",
    formulaParts: [
      { label: "FTM", value: "Made free throws." },
      { label: "FTA", value: "Free-throw attempts." },
    ],
    betterDirection: "higher",
    thresholds: [
      { label: "Elite", rangeLabel: "88%+", interpretation: "Trusted late-game foul shooter.", tone: "elite" },
      { label: "Good", rangeLabel: "78% to 87.9%", interpretation: "Solid line efficiency.", tone: "good" },
      { label: "Average", rangeLabel: "72% to 77.9%", interpretation: "Manageable foul shooting.", tone: "average" },
      { label: "Poor", rangeLabel: "Below 72%", interpretation: "Leaves points at the line.", tone: "warning" },
    ],
    leagueAverageLabel: "League average is usually around 77% to 78%.",
    impactTags: ["Late-game value", "Scoring efficiency", "Shot touch"],
  },
  {
    key: "Win %",
    sport: "NBA",
    displayName: "Win %",
    aliases: ["win percentage", "winning percentage", "pct"],
    shortDescription: "Share of games a team has won.",
    plainEnglishExplanation: "Win percentage is the standings shorthand for how often a team wins. It makes teams with different game totals easier to compare than raw wins alone.",
    formulaText: "Wins / (Wins + Losses)",
    formulaParts: [
      { label: "Wins", value: "Games finished with a win." },
      { label: "Games played", value: "Wins plus losses." },
    ],
    betterDirection: "higher",
    thresholds: [
      { label: "Contender pace", rangeLabel: ".650+", interpretation: "Winning at a high level.", tone: "elite" },
      { label: "Strong", rangeLabel: ".550 to .649", interpretation: "Solid playoff-quality pace.", tone: "good" },
      { label: "Average", rangeLabel: ".450 to .549", interpretation: "Middle-of-the-pack results.", tone: "average" },
      { label: "Struggling", rangeLabel: "Below .450", interpretation: "Losing more often than winning.", tone: "warning" },
    ],
    leagueAverageLabel: "League average always centers around .500.",
    impactTags: ["Standings", "Team performance", "Season pace"],
  },
  {
    key: "TS%",
    sport: "NBA",
    displayName: "TS%",
    aliases: ["true shooting", "true shooting percentage"],
    shortDescription: "Overall scoring efficiency including twos, threes, and free throws.",
    plainEnglishExplanation: "TS% is the best quick efficiency stat for scorers because it values all the main ways players score, not just field goals.",
    formulaText: "Points / (2 x (Field Goal Attempts + 0.44 x Free Throw Attempts))",
    formulaParts: [
      { label: "Points", value: "All points scored." },
      { label: "Shot possessions", value: "Field-goal attempts plus an estimate for free-throw possessions." },
      { label: "Times 2", value: "Converts the denominator into points-per-shot scale." },
    ],
    betterDirection: "higher",
    thresholds: [
      { label: "Elite", rangeLabel: "63%+", interpretation: "High-end scoring efficiency.", tone: "elite" },
      { label: "Good", rangeLabel: "58% to 62.9%", interpretation: "Strong shot value.", tone: "good" },
      { label: "Average", rangeLabel: "55% to 57.9%", interpretation: "Near league norm.", tone: "average" },
      { label: "Inefficient", rangeLabel: "Below 55%", interpretation: "Scoring costs too many possessions.", tone: "warning" },
    ],
    leagueAverageLabel: "League average is usually around 57% to 58%.",
    impactTags: ["Efficiency", "Shot value", "Scoring quality"],
    advancedNote: "TS% does not capture turnovers or passing. It measures scoring efficiency only.",
  },
  {
    key: "PER",
    sport: "NBA",
    displayName: "PER",
    aliases: ["player efficiency rating"],
    shortDescription: "Box-score-based per-minute productivity summary.",
    plainEnglishExplanation: "PER rolls many box score stats into one per-minute number. It is useful as a quick production snapshot, but it is not a full modern impact metric.",
    formulaText: "Weighted box score production per minute, pace-adjusted and normalized so league average equals 15",
    formulaParts: [
      { label: "Positive box score events", value: "Points, rebounds, assists, steals, blocks, and more add value." },
      { label: "Negative events", value: "Misses, turnovers, and fouls reduce value." },
      { label: "Normalization", value: "The scale is set so 15 is league average." },
    ],
    betterDirection: "higher",
    thresholds: [
      { label: "Star level", rangeLabel: "24+", interpretation: "Very strong statistical production.", tone: "elite" },
      { label: "Good", rangeLabel: "18 to 23.9", interpretation: "Above-average box score impact.", tone: "good" },
      { label: "Average", rangeLabel: "15 to 17.9", interpretation: "League-average production.", tone: "average" },
      { label: "Below average", rangeLabel: "Below 15", interpretation: "Limited overall box score output.", tone: "warning" },
    ],
    leagueAverageLabel: "League average is fixed at 15 by design.",
    impactTags: ["Box score summary", "Per-minute production", "Historical comparison"],
    advancedNote: "PER can overrate volume and underrate defense, spacing, and off-ball value.",
  },
  {
    key: "+/-",
    sport: "NBA",
    displayName: "+/-",
    aliases: ["plus minus", "+-"],
    shortDescription: "Point margin while a player is on the floor.",
    plainEnglishExplanation: "Plus-minus tells you whether the team outscores opponents with a player in the game. It is useful, but lineup context matters a lot.",
    formulaText: "Team points scored while on court minus opponent points scored while on court",
    formulaParts: [
      { label: "Team points", value: "Points your team scores during the player's minutes." },
      { label: "Opponent points", value: "Points allowed during those same minutes." },
    ],
    betterDirection: "higher",
    thresholds: [
      { label: "Very positive", rangeLabel: "+8 or better", interpretation: "Lineups are crushing opponents.", tone: "elite" },
      { label: "Positive", rangeLabel: "+2 to +7", interpretation: "Usually helping winning margin.", tone: "good" },
      { label: "Neutral", rangeLabel: "-1 to +1", interpretation: "Roughly even results.", tone: "average" },
      { label: "Negative", rangeLabel: "-2 or worse", interpretation: "Team is losing those minutes.", tone: "warning" },
    ],
    leagueAverageLabel: "Single-game plus-minus swings wildly with lineup context.",
    impactTags: ["On-court margin", "Lineup performance", "Game flow"],
    advancedNote: "Raw plus-minus is noisy. Over larger samples, lineup quality and opponent strength still matter a lot.",
  },
  {
    key: "USG%",
    sport: "NBA",
    displayName: "USG%",
    aliases: ["usage", "usage rate"],
    shortDescription: "Share of team possessions a player finishes while on the floor.",
    plainEnglishExplanation: "Usage rate estimates how often a possession ends with that player's shot, turnover, or drawn shooting foul. It is a role-size stat, not a quality stat.",
    formulaText: "Estimate of player-used possessions divided by team possessions while on court",
    formulaParts: [
      { label: "Player-used possessions", value: "Built from field-goal attempts, turnovers, and free-throw trips." },
      { label: "Team possessions", value: "The offense available during the player's minutes." },
    ],
    betterDirection: "contextual",
    thresholds: [
      { label: "Primary engine", rangeLabel: "30%+", interpretation: "Massive offensive burden.", tone: "elite" },
      { label: "Major role", rangeLabel: "24% to 29.9%", interpretation: "Clear lead or co-lead creator.", tone: "good" },
      { label: "Balanced role", rangeLabel: "18% to 23.9%", interpretation: "Normal starter usage.", tone: "average" },
      { label: "Low-usage role", rangeLabel: "Below 18%", interpretation: "Mostly play finisher or connector.", tone: "warning" },
    ],
    leagueAverageLabel: "Usage is role-driven; league average starters are often near 20% to 22%.",
    impactTags: ["Role size", "Offensive burden", "Shot creation context"],
    advancedNote: "High usage can be good or bad. The key question is whether the player remains efficient at that volume.",
  },
  {
    key: "BPG",
    sport: "NBA",
    displayName: "BPG",
    aliases: ["blocks per game"],
    shortDescription: "Average blocks recorded per game.",
    plainEnglishExplanation: "BPG captures how often a player rejects shots. It can signal rim protection, timing, and defensive presence near the basket.",
    formulaText: "Blocks / Games Played",
    formulaParts: [
      { label: "Blocks", value: "Shot attempts legally blocked." },
      { label: "Games Played", value: "Turns totals into a per-game average." },
    ],
    betterDirection: "higher",
    thresholds: [
      { label: "Rim eraser", rangeLabel: "2.0+", interpretation: "Strong shot-blocking presence.", tone: "elite" },
      { label: "Good", rangeLabel: "1.2 to 1.9", interpretation: "Useful interior deterrence.", tone: "good" },
      { label: "Average", rangeLabel: "0.6 to 1.1", interpretation: "Some block activity.", tone: "average" },
      { label: "Low", rangeLabel: "Below 0.6", interpretation: "Little shot-blocking volume.", tone: "warning" },
    ],
    leagueAverageLabel: "Block volume depends heavily on position and scheme.",
    impactTags: ["Rim protection", "Defense", "Interior presence"],
  },
  {
    key: "SPG",
    sport: "NBA",
    displayName: "SPG",
    aliases: ["steals per game"],
    shortDescription: "Average steals recorded per game.",
    plainEnglishExplanation: "SPG measures how often a defender creates takeaways. Steals can flip possessions quickly and create easy transition offense.",
    formulaText: "Steals / Games Played",
    formulaParts: [
      { label: "Steals", value: "Possessions directly taken away." },
      { label: "Games Played", value: "Turns totals into a nightly rate." },
    ],
    betterDirection: "higher",
    thresholds: [
      { label: "Disruptive", rangeLabel: "1.8+", interpretation: "High-end hands and anticipation.", tone: "elite" },
      { label: "Good", rangeLabel: "1.2 to 1.7", interpretation: "Creates extra possessions.", tone: "good" },
      { label: "Average", rangeLabel: "0.8 to 1.1", interpretation: "Normal steal rate.", tone: "average" },
      { label: "Low", rangeLabel: "Below 0.8", interpretation: "Not a major takeaway source.", tone: "warning" },
    ],
    leagueAverageLabel: "Steal volume depends on role, scheme, and gambling style.",
    impactTags: ["Turnovers forced", "Perimeter defense", "Transition creation"],
  },
  {
    key: "ORTG",
    sport: "NBA",
    displayName: "ORTG",
    aliases: ["offensive rating", "off rating"],
    shortDescription: "Points scored per 100 possessions.",
    plainEnglishExplanation: "Offensive rating tells you how efficient an offense is once pace is stripped out. It answers how many points a team or player context creates every 100 possessions.",
    formulaText: "(Points Scored / Possessions) x 100",
    formulaParts: [
      { label: "Points Scored", value: "Total offensive points." },
      { label: "Possessions", value: "Estimated opportunities to score." },
      { label: "Times 100", value: "Standardizes the number for easier comparison." },
    ],
    betterDirection: "higher",
    thresholds: [
      { label: "Elite offense", rangeLabel: "120+", interpretation: "High-end scoring efficiency.", tone: "elite" },
      { label: "Strong", rangeLabel: "115 to 119.9", interpretation: "Above-average attack.", tone: "good" },
      { label: "Average", rangeLabel: "111 to 114.9", interpretation: "Near league norm.", tone: "average" },
      { label: "Poor", rangeLabel: "Below 111", interpretation: "Struggling to score efficiently.", tone: "warning" },
    ],
    leagueAverageLabel: "League average usually sits around the low-to-mid 110s.",
    impactTags: ["Efficiency", "Pace-neutral offense", "Team context"],
  },
  {
    key: "DRTG",
    sport: "NBA",
    displayName: "DRTG",
    aliases: ["defensive rating", "def rating"],
    shortDescription: "Points allowed per 100 possessions.",
    plainEnglishExplanation: "Defensive rating measures how hard a team or lineup makes life for opponents once pace is removed. Lower is better because it means fewer points allowed for each 100 trips.",
    formulaText: "(Points Allowed / Possessions) x 100",
    formulaParts: [
      { label: "Points Allowed", value: "What the opponent scores." },
      { label: "Possessions", value: "Estimated defensive trips faced." },
      { label: "Times 100", value: "Standardizes the rate." },
    ],
    betterDirection: "lower",
    thresholds: [
      { label: "Elite defense", rangeLabel: "108 or lower", interpretation: "Shuts down efficient scoring.", tone: "elite" },
      { label: "Good", rangeLabel: "109 to 113", interpretation: "Above-average defense.", tone: "good" },
      { label: "Average", rangeLabel: "114 to 116", interpretation: "Near league norm.", tone: "average" },
      { label: "Poor", rangeLabel: "Above 116", interpretation: "Giving up too much efficiency.", tone: "warning" },
    ],
    leagueAverageLabel: "League average usually lives in the low-to-mid 110s.",
    impactTags: ["Defense", "Pace-neutral view", "Team resistance"],
  },
  {
    key: "NET RTG",
    sport: "NBA",
    displayName: "NET RTG",
    aliases: ["net rating", "netrtg"],
    shortDescription: "Offensive rating minus defensive rating.",
    plainEnglishExplanation: "Net rating is the clean margin stat. It estimates how many points per 100 possessions a team or lineup outscores opponents by.",
    formulaText: "ORTG - DRTG",
    formulaParts: [
      { label: "ORTG", value: "Points scored per 100 possessions." },
      { label: "DRTG", value: "Points allowed per 100 possessions." },
    ],
    betterDirection: "higher",
    thresholds: [
      { label: "Contender level", rangeLabel: "+8 or better", interpretation: "Dominant overall profile.", tone: "elite" },
      { label: "Strong", rangeLabel: "+3 to +7.9", interpretation: "Solid winning-level performance.", tone: "good" },
      { label: "Average", rangeLabel: "-2 to +2.9", interpretation: "Roughly neutral quality.", tone: "average" },
      { label: "Negative", rangeLabel: "Below -2", interpretation: "Getting outplayed overall.", tone: "warning" },
    ],
    leagueAverageLabel: "League average is always around 0 by definition.",
    impactTags: ["Margin quality", "Team strength", "Lineup evaluation"],
    advancedNote: "Net rating is more meaningful over larger samples. Small samples can swing fast with schedule and lineup variance.",
  },
] as const satisfies readonly StatGlossaryEntry[];

const NFL_STATS = [
  {
    key: "Passer Rating",
    sport: "NFL",
    displayName: "Passer Rating",
    aliases: ["rating", "qb passer rating"],
    shortDescription: "Traditional quarterback passing efficiency formula.",
    plainEnglishExplanation: "Passer Rating blends completion rate, yards per attempt, touchdowns, and interceptions into one familiar QB number. It is quick and widely used, but not fully modern.",
    formulaText: "NFL formula built from completion %, yards per attempt, TD rate, and INT rate on a 0 to 158.3 scale",
    formulaParts: [
      { label: "Completion component", value: "Rewards accurate passing." },
      { label: "Yards component", value: "Rewards efficiency and ball movement." },
      { label: "TD and INT components", value: "Rewards scoring throws and punishes mistakes." },
    ],
    betterDirection: "higher",
    thresholds: [
      { label: "Elite", rangeLabel: "100+", interpretation: "High-end passing efficiency.", tone: "elite" },
      { label: "Good", rangeLabel: "90 to 99.9", interpretation: "Above-average passing.", tone: "good" },
      { label: "Average", rangeLabel: "85 to 89.9", interpretation: "Manageable baseline play.", tone: "average" },
      { label: "Poor", rangeLabel: "Below 85", interpretation: "Inefficient or mistake-heavy passing.", tone: "warning" },
    ],
    leagueAverageLabel: "League average is usually in the high 80s to low 90s.",
    impactTags: ["Passing efficiency", "QB play", "Traditional benchmark"],
    advancedNote: "Passer Rating ignores sacks, rushing, situation, and difficulty. QBR and EPA go further.",
  },
  {
    key: "QBR",
    sport: "NFL",
    displayName: "QBR",
    aliases: ["total qbr"],
    shortDescription: "Context-heavy quarterback value metric on a 0 to 100 scale.",
    plainEnglishExplanation: "QBR tries to measure total quarterback contribution, including passing, rushing, game situation, and opponent context. It aims to tell you how much the QB drove winning.",
    formulaText: "Proprietary ESPN model using EPA-style play value, game context, opponent, and quarterback credit allocation",
    formulaParts: [
      { label: "Play value", value: "Grades how valuable each QB play was." },
      { label: "Context", value: "Weights down-and-distance, game state, and leverage." },
      { label: "Quarterback credit", value: "Attempts to isolate what the QB controlled." },
    ],
    betterDirection: "higher",
    thresholds: [
      { label: "Elite", rangeLabel: "70+", interpretation: "Driving high-end QB value.", tone: "elite" },
      { label: "Good", rangeLabel: "60 to 69.9", interpretation: "Clearly above average.", tone: "good" },
      { label: "Average", rangeLabel: "50 to 59.9", interpretation: "Around league middle.", tone: "average" },
      { label: "Poor", rangeLabel: "Below 50", interpretation: "Below-average QB impact.", tone: "warning" },
    ],
    leagueAverageLabel: "League average is centered near 50.",
    impactTags: ["QB impact", "Situation-aware value", "Winning context"],
    advancedNote: "QBR is not fully transparent because the formula is proprietary, so it is best used alongside open stats.",
  },
  {
    key: "YPC",
    sport: "NFL",
    displayName: "YPC",
    aliases: ["yards per carry"],
    shortDescription: "Average rushing yards gained per carry.",
    plainEnglishExplanation: "YPC is the easiest rushing efficiency stat to read. It shows how much ground a runner gains on each attempt, but it can swing a lot on a few long runs.",
    formulaText: "Rushing Yards / Carries",
    formulaParts: [
      { label: "Rushing Yards", value: "Total yards on runs." },
      { label: "Carries", value: "Rushing attempts." },
    ],
    betterDirection: "higher",
    thresholds: [
      { label: "Explosive", rangeLabel: "5.0+", interpretation: "Consistently creating chunk gains.", tone: "elite" },
      { label: "Good", rangeLabel: "4.4 to 4.9", interpretation: "Above-average rushing efficiency.", tone: "good" },
      { label: "Average", rangeLabel: "4.0 to 4.3", interpretation: "Normal rushing output.", tone: "average" },
      { label: "Low", rangeLabel: "Below 4.0", interpretation: "Run game is grinding.", tone: "warning" },
    ],
    leagueAverageLabel: "League average is usually a little above 4.2 YPC.",
    impactTags: ["Rushing efficiency", "Explosiveness", "Run game health"],
    advancedNote: "YPC is very sensitive to explosive runs, blocking, and down-and-distance. Success rate often adds better context.",
  },
  {
    key: "Yards per Attempt",
    sport: "NFL",
    displayName: "Yards per Attempt",
    aliases: ["yards/attempt", "yards per pass attempt", "ypa"],
    shortDescription: "Average passing yards gained per attempt.",
    plainEnglishExplanation: "Yards per attempt is a strong quick stat for passing efficiency because it blends accuracy with downfield value better than completion rate alone.",
    formulaText: "Passing Yards / Pass Attempts",
    formulaParts: [
      { label: "Passing Yards", value: "Total yards gained through the air." },
      { label: "Pass Attempts", value: "Throws that count as attempts." },
    ],
    betterDirection: "higher",
    thresholds: [
      { label: "Elite", rangeLabel: "8.0+", interpretation: "High-value passing efficiency.", tone: "elite" },
      { label: "Good", rangeLabel: "7.2 to 7.9", interpretation: "Strong passing production.", tone: "good" },
      { label: "Average", rangeLabel: "6.6 to 7.1", interpretation: "Normal NFL efficiency.", tone: "average" },
      { label: "Low", rangeLabel: "Below 6.6", interpretation: "Passing game is too inefficient.", tone: "warning" },
    ],
    leagueAverageLabel: "League average is usually around 7.0 yards per attempt.",
    impactTags: ["Passing efficiency", "Explosiveness", "QB effectiveness"],
  },
  {
    key: "Completion %",
    sport: "NFL",
    displayName: "Completion %",
    aliases: ["completion percentage", "cmp%", "comp%"],
    shortDescription: "Share of pass attempts completed.",
    plainEnglishExplanation: "Completion percentage is the simplest accuracy stat. It shows how often a quarterback completes passes, though short throws can inflate it.",
    formulaText: "Completions / Attempts",
    formulaParts: [
      { label: "Completions", value: "Pass attempts caught in bounds." },
      { label: "Attempts", value: "All official pass attempts." },
    ],
    betterDirection: "higher",
    thresholds: [
      { label: "Elite", rangeLabel: "69%+", interpretation: "High-end completion efficiency.", tone: "elite" },
      { label: "Good", rangeLabel: "65% to 68.9%", interpretation: "Above-average accuracy.", tone: "good" },
      { label: "Average", rangeLabel: "62% to 64.9%", interpretation: "Normal completion rate.", tone: "average" },
      { label: "Low", rangeLabel: "Below 62%", interpretation: "Accuracy or throw quality is lagging.", tone: "warning" },
    ],
    leagueAverageLabel: "League average is usually around 64% to 65%.",
    impactTags: ["Accuracy", "Passing baseline", "QB consistency"],
    advancedNote: "Completion % depends heavily on throw depth, scheme, and screen volume. Pair it with air yards or yards per attempt.",
  },
  {
    key: "YAC",
    sport: "NFL",
    displayName: "YAC",
    aliases: ["yards after catch"],
    shortDescription: "Yards gained after a receiver secures the ball.",
    plainEnglishExplanation: "YAC measures what happens once the catch is already made. It highlights open-field burst, tackle breaking, and how much a scheme creates space.",
    formulaText: "Receiving yards gained after the point of catch",
    formulaParts: [
      { label: "Catch point", value: "Where the receiver first secures the pass." },
      { label: "After-catch yards", value: "Distance gained beyond that point." },
    ],
    betterDirection: "contextual",
    thresholds: [
      { label: "Big-play threat", rangeLabel: "6.0+ YAC/reception", interpretation: "Generating major damage after the catch.", tone: "elite" },
      { label: "Good", rangeLabel: "4.5 to 5.9", interpretation: "Useful after-catch value.", tone: "good" },
      { label: "Average", rangeLabel: "3.5 to 4.4", interpretation: "Normal YAC profile.", tone: "average" },
      { label: "Low", rangeLabel: "Below 3.5", interpretation: "Little extra yardage after the catch.", tone: "warning" },
    ],
    leagueAverageLabel: "Context matters more than raw totals, so YAC per catch is often the cleaner view.",
    impactTags: ["Open-field ability", "Receiver fit", "Scheme spacing"],
    advancedNote: "High YAC can come from player talent, easy throws, or offensive design. It should be read with air yards.",
  },
  {
    key: "Air Yards",
    sport: "NFL",
    displayName: "Air Yards",
    aliases: ["air yards per target", "adot", "average depth of target"],
    shortDescription: "How far the ball travels in the air toward a receiver or on a QB attempt.",
    plainEnglishExplanation: "Air yards tell you how aggressive the passing game is before the catch. Higher depth can mean bigger upside, but it often lowers completion rate.",
    formulaText: "Total yards the ball travels past the line of scrimmage before the catch or incompletion",
    formulaParts: [
      { label: "Throw depth", value: "Distance from the line of scrimmage to the target point." },
      { label: "Target volume", value: "Often paired with per-target or average depth views." },
    ],
    betterDirection: "contextual",
    thresholds: [
      { label: "Deep role", rangeLabel: "12+ aDOT", interpretation: "Stretching the field vertically.", tone: "elite" },
      { label: "Intermediate", rangeLabel: "8 to 11.9", interpretation: "Balanced downfield usage.", tone: "good" },
      { label: "Short-area", rangeLabel: "5 to 7.9", interpretation: "Working underneath often.", tone: "average" },
      { label: "Very shallow", rangeLabel: "Below 5", interpretation: "Mostly quick-game usage.", tone: "warning" },
    ],
    leagueAverageLabel: "Air-yards context depends on position, role, and offensive design.",
    impactTags: ["Route depth", "Target quality", "Passing aggression"],
    advancedNote: "More air yards are not automatically better. Deep roles trade catch rate for explosive upside.",
  },
  {
    key: "EPA",
    sport: "NFL",
    displayName: "EPA",
    aliases: ["expected points added"],
    shortDescription: "How much a play changes the offense's expected points.",
    plainEnglishExplanation: "EPA measures play value in scoring terms. Positive EPA means the play improved scoring outlook; negative EPA means it hurt the offense.",
    formulaText: "Expected Points after the play minus Expected Points before the play",
    formulaParts: [
      { label: "Expected points before", value: "Scoring outlook based on down, distance, field position, and time." },
      { label: "Expected points after", value: "The updated scoring outlook once the play ends." },
      { label: "Difference", value: "How much value the play created or lost." },
    ],
    betterDirection: "higher",
    thresholds: [
      { label: "Excellent", rangeLabel: "0.20+ EPA/play", interpretation: "Driving high-value offense.", tone: "elite" },
      { label: "Good", rangeLabel: "0.05 to 0.19", interpretation: "Consistently positive contribution.", tone: "good" },
      { label: "Average", rangeLabel: "-0.04 to 0.04", interpretation: "Near neutral overall value.", tone: "average" },
      { label: "Negative", rangeLabel: "Below -0.04", interpretation: "Losing value on average.", tone: "warning" },
    ],
    leagueAverageLabel: "At the play level, 0 is neutral and positive is better.",
    impactTags: ["Play value", "Situational efficiency", "Winning impact"],
    advancedNote: "EPA is powerful, but it is very context-heavy. Down, distance, game state, and opponent all matter.",
  },
] as const satisfies readonly StatGlossaryEntry[];

export const STAT_GLOSSARY = [
  ...MLB_STATS,
  ...NBA_STATS,
  ...NFL_STATS,
] as const satisfies readonly StatGlossaryEntry[];

function normalizeStatToken(value: string): string {
  return value.trim().toLowerCase().replace(/\s+/g, " ");
}

function candidateKeys(entry: StatGlossaryEntry): string[] {
  return [entry.key, entry.displayName, ...entry.aliases].map(normalizeStatToken);
}

export function findStatGlossaryEntry(statKey: string, sport?: StatSport): StatGlossaryEntry | null {
  const normalizedKey = normalizeStatToken(statKey);
  const bySport = sport
    ? STAT_GLOSSARY.filter((entry) => entry.sport === sport)
    : STAT_GLOSSARY;

  return bySport.find((entry) => candidateKeys(entry).includes(normalizedKey)) ?? null;
}

export function hasStatGlossaryEntry(statKey: string, sport?: StatSport): boolean {
  return Boolean(findStatGlossaryEntry(statKey, sport));
}
