"use client";

import { useCallback, useEffect, useState } from "react";
import type { WidgetCommonProps, WidgetMeta } from "@/components/widgets/types";
import { MLB_TEAM_OPTIONS } from "@/lib/providers/mlb/teamMap";

type CommentaryInfo = {
  text: string;
  mode: string;
  generatedBy: string;
  inputsUsed: string[];
  cachedAt: string | null;
  fingerprint: string;
  isFallback: boolean;
};

type CommentaryGame = {
  gameId: string;
  awayTeam: string;
  homeTeam: string;
  gameTime: string;
  division: string;
  commentary: CommentaryInfo;
  inputs?: Record<string, unknown>;
};

type CommentaryData = {
  dateUsed: string;
  games: CommentaryGame[];
  noTeamGame: boolean;
  noTeamGameMessage: string | null;
};

type CommentaryResponse = {
  data: CommentaryData | null;
  meta?: WidgetMeta | null;
  error?: string | null;
};

function formatGameTime(dateStr: string): string {
  try {
    return new Date(dateStr).toLocaleTimeString("en-US", {
      hour: "numeric",
      minute: "2-digit",
      timeZoneName: "short",
      timeZone: "America/New_York",
    });
  } catch {
    return dateStr;
  }
}

function parseTeamKey(query: string): string | null {
  const upper = query.trim().toUpperCase();
  if (!upper) return null;
  const byKey = MLB_TEAM_OPTIONS.find((t) => t.key === upper);
  if (byKey) return byKey.key;
  const byName = MLB_TEAM_OPTIONS.find((t) => t.name.toUpperCase() === upper);
  if (byName) return byName.key;
  const suffix = query.match(/\(([A-Za-z]{2,4})\)\s*$/)?.[1]?.toUpperCase();
  if (suffix && MLB_TEAM_OPTIONS.find((t) => t.key === suffix)) return suffix;
  return null;
}

function CommentaryCard({
  game,
  isAdvanced,
}: {
  game: CommentaryGame;
  isAdvanced: boolean;
}) {
  const [showInputs, setShowInputs] = useState(false);
  const { commentary } = game;

  return (
    <div className="rounded border border-white/10 bg-neutral-800/40 p-2.5 flex flex-col gap-1.5">
      <div className="flex items-start justify-between gap-2">
        <div>
          <span className="text-[12px] font-semibold text-zinc-100">{game.awayTeam}</span>
          <span className="text-[10px] text-zinc-500 mx-1.5">@</span>
          <span className="text-[12px] font-semibold text-zinc-100">{game.homeTeam}</span>
        </div>
        <span className="text-[10px] text-zinc-500 whitespace-nowrap">{formatGameTime(game.gameTime)}</span>
      </div>

      <p className="text-[11px] text-zinc-300 leading-snug">{commentary.text}</p>

      {commentary.isFallback && (
        <span className="text-[9px] text-amber-500/80 italic">Rules-based</span>
      )}

      {isAdvanced && game.inputs && (
        <div>
          <button
            type="button"
            className="text-[9px] text-zinc-600 hover:text-zinc-400 transition-colors"
            onClick={() => setShowInputs((prev) => !prev)}
          >
            {showInputs ? "▲" : "▼"} Inputs used ({commentary.inputsUsed.length})
          </button>
          {showInputs && (
            <div className="mt-1 flex flex-col gap-0.5">
              {commentary.inputsUsed.map((input) => (
                <span key={input} className="text-[9px] text-zinc-600 font-mono">• {input}</span>
              ))}
            </div>
          )}
        </div>
      )}

      <div className="flex items-center gap-1.5 flex-wrap text-[9px] text-zinc-600">
        <span>Generated by {commentary.generatedBy}</span>
        <span>·</span>
        <span>{commentary.inputsUsed.length} inputs</span>
        <span>·</span>
        <span>{commentary.cachedAt ? "cached" : "fresh"}</span>
        {isAdvanced && (
          <>
            <span>·</span>
            <span className="font-mono">{commentary.fingerprint.slice(0, 8)}</span>
          </>
        )}
      </div>
    </div>
  );
}

export default function MlbMatchupCommentaryWidget(props: WidgetCommonProps) {
  const initialTeamKey = (props.config?.teamKey as string | undefined) ?? "";
  const [teamQuery, setTeamQuery] = useState(initialTeamKey);
  const [activeTeamKey, setActiveTeamKey] = useState(initialTeamKey);
  const [data, setData] = useState<CommentaryData | null>(null);
  const [meta, setMeta] = useState<WidgetMeta | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const isAdvanced = props.mode === "ADVANCED";

  const fetchData = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const params = new URLSearchParams({
        mode: props.mode.toLowerCase(),
        dataMode: props.dataMode,
        cacheBust: String(props.refreshTick),
      });
      if (activeTeamKey) params.set("teamKey", activeTeamKey);
      const res = await fetch(`/api/widgets/mlb-matchup-commentary?${params}`);
      const body: CommentaryResponse = await res.json();
      if (!res.ok) throw new Error(body.error ?? "Failed to load commentary");
      setData(body.data ?? null);
      setMeta(body.meta ?? null);
      setError(body.error ?? null);
    } catch (fetchError) {
      setError(String(fetchError));
    } finally {
      setLoading(false);
    }
  }, [activeTeamKey, props.mode, props.dataMode, props.refreshTick]);

  useEffect(() => {
    void fetchData();
  }, [fetchData]);

  function handleTeamSubmit(e: React.FormEvent) {
    e.preventDefault();
    const resolved = parseTeamKey(teamQuery) ?? "";
    setActiveTeamKey(resolved);
    void props.onPersist({ config: { ...props.config, teamKey: resolved } });
  }

  function handleClear() {
    setTeamQuery("");
    setActiveTeamKey("");
    void props.onPersist({ config: { ...props.config, teamKey: "" } });
  }

  return (
    <div className="flex flex-col gap-2 p-3 h-full text-white">
      {/* Header */}
      <div className="flex items-center justify-between gap-2">
        <div className="text-[11px] font-semibold text-zinc-200 leading-none">
          MLB Matchup Commentary
          {data?.dateUsed && (
            <span className="text-zinc-500 font-normal"> · {data.dateUsed}</span>
          )}
        </div>
        <span className="text-[9px] text-zinc-600 uppercase tracking-wide font-medium">MLB</span>
      </div>

      {/* Team selector */}
      {!props.locked && (
        <form onSubmit={handleTeamSubmit} className="flex items-center gap-1.5">
          <input
            type="text"
            list="mlb-teams-commentary"
            value={teamQuery}
            onChange={(e) => setTeamQuery(e.target.value)}
            placeholder="Filter by team (e.g. NYY)"
            className="flex-1 text-[11px] rounded border border-zinc-700 bg-zinc-900 px-2 py-1 text-zinc-200 placeholder:text-zinc-600 min-w-0"
          />
          <datalist id="mlb-teams-commentary">
            {MLB_TEAM_OPTIONS.map((t) => (
              <option key={t.key} value={`${t.name} (${t.key})`} />
            ))}
          </datalist>
          <button
            type="submit"
            className="text-[10px] text-zinc-400 border border-zinc-700 rounded px-2 py-1 hover:text-zinc-200 transition-colors shrink-0"
          >
            Go
          </button>
          {activeTeamKey && (
            <button
              type="button"
              onClick={handleClear}
              className="text-[10px] text-zinc-500 hover:text-zinc-300 transition-colors shrink-0"
            >
              Clear
            </button>
          )}
        </form>
      )}

      {/* Body */}
      {loading && (
        <div className="flex-1 flex items-center justify-center">
          <span className="text-[11px] text-zinc-500 animate-pulse">
            Generating matchup analysis...
          </span>
        </div>
      )}

      {!loading && error && (
        <div className="rounded bg-zinc-800 border border-zinc-700 px-3 py-2 text-[11px] text-amber-400">
          {error}
        </div>
      )}

      {!loading && !error && data?.noTeamGame && (
        <div className="text-[11px] text-zinc-500 mt-1">
          {data.noTeamGameMessage ?? `No game scheduled for ${activeTeamKey} today.`}
        </div>
      )}

      {!loading && !error && data && !data.noTeamGame && data.games.length === 0 && (
        <div className="text-[11px] text-zinc-500 mt-1">No MLB games scheduled today.</div>
      )}

      {!loading && !error && data && data.games.length > 0 && (
        <div className="flex-1 overflow-y-auto flex flex-col gap-2 min-h-0">
          {data.games.map((game) => (
            <CommentaryCard key={game.gameId} game={game} isAdvanced={isAdvanced} />
          ))}
        </div>
      )}

      {/* Footer */}
      <div className="mt-auto pt-1.5 border-t border-white/5 flex flex-col gap-0.5">
        <p className="text-[9px] text-zinc-600 italic">
          AI commentary is for educational purposes only. Not betting advice.
        </p>
        {meta && (
          <div className="flex items-center justify-between">
            <span className="text-[9px] text-zinc-700">
              Updated {new Date(meta.updatedAt).toLocaleTimeString()} · Source ESPN
            </span>
            <button
              type="button"
              className="text-[9px] text-zinc-700 hover:text-zinc-500 transition-colors"
              onClick={() => props.onReportBug({ widget: "mlb_matchup_commentary", meta })}
            >
              Report issue
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
