"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useDebouncedValue } from "@/components/hooks/useDebouncedValue";
import StatLabel from "@/components/stats/StatLabel";
import TabsRow from "@/components/widgets/shared/TabsRow";
import type { WidgetCommonProps, WidgetMeta } from "@/components/widgets/types";
import { getGuestWatchlist, type GuestWatchlistItem } from "@/lib/guest/watchlist";
import type { Envelope, PlayerProfile, PlayerSearchResult, SportKey, TeamSearchResult } from "@/lib/types/players";
import type { PlayerInsights, TeamAdvanced } from "@/lib/types/playerInsights";
import type { TeamStatus } from "@/lib/types/teamStatus";
import { stableKey } from "@/lib/utils/stableKey";

type WatchItem = GuestWatchlistItem;

type WatchlistResponse = {
  items?: WatchItem[];
  error?: string;
};

type PlayerSearchResultMin = {
  playerId: string;
  fullName: string;
  teamName?: string;
  position?: string;
  headshot?: string;
};

type PlayerWatchlistBySport = Record<SportKey, PlayerSearchResultMin[]>;

type TeamWatchlistBySport = Record<SportKey, string[]>;

type TeamWatchlistNamesBySport = Record<SportKey, Record<string, string>>;
type TeamProviderIds = {
  apiSportsTeamId?: string;
  espnTeamId?: string;
};
type TeamProviderIdsBySport = Record<SportKey, Record<string, TeamProviderIds>>;

type ViewMode = "teams" | "players";
type TeamsAdvancedEnvelope = Envelope<{ sport: SportKey; teams: TeamAdvanced[] }>;
type PlayerInsightsBatchEnvelope = Envelope<{ sport: SportKey; players: PlayerInsights[] }>;
type TeamSearchEnvelope = Envelope<TeamSearchResult[]>;

const TEAM_LIMIT = 10;
const PLAYER_LIMIT = 10;
const TEAM_STATUS_REFRESH_MS = 30_000;
const PLAYER_INSIGHTS_REFRESH_MS = 60_000;

// Canonical team abbreviations per sport. Used to detect and repair legacy persisted keys that
// were generated by the name-acronym fallback (e.g. "TBJ" for Toronto Blue Jays).
const MLB_CANONICAL_KEYS = new Set<string>([
  "NYM","NYY","LAD","BOS","CHC","HOU","ATL","PHI","SDP","SFG",
  "STL","MIL","CIN","PIT","COL","ARI","SEA","TEX","OAK","MIN",
  "CLE","DET","KCR","CHW","TBR","BAL","WSN","MIA","TOR","LAA",
]);
const NBA_CANONICAL_KEYS = new Set<string>([
  "ATL","BOS","NOP","CHI","CLE","DAL","DEN","DET","GSW","HOU",
  "IND","LAC","LAL","MIA","MIL","MIN","BKN","NYK","ORL","PHI",
  "PHX","POR","SAC","SAS","OKC","UTA","WAS","TOR","MEM","CHA",
]);

function isCanonicalTeamKey(sport: SportKey, key: string): boolean {
  if (sport === "mlb") return MLB_CANONICAL_KEYS.has(key);
  if (sport === "nba") return NBA_CANONICAL_KEYS.has(key);
  return true; // NFL uses a separate path; don't validate here
}

const MODE_TABS = [
  { key: "teams", label: "Teams" },
  { key: "players", label: "Players" },
] as const;

const SPORT_TABS = [
  { key: "nfl", label: "NFL" },
  { key: "mlb", label: "MLB" },
  { key: "nba", label: "NBA" },
] as const;

export function addTeamToSportWatchlist(
  current: Record<SportKey, string[]>,
  sport: SportKey,
  teamKey: string,
): Record<SportKey, string[]> {
  const normalized = teamKey.trim().toUpperCase();
  if (!normalized) {
    return current;
  }
  const sportTeams = current[sport] ?? [];
  if (sportTeams.includes(normalized)) {
    return current;
  }
  return {
    ...current,
    [sport]: [...sportTeams, normalized],
  };
}

export function upsertTeamProviderIds(
  current: Record<SportKey, Record<string, { apiSportsTeamId?: string; espnTeamId?: string }>>,
  sport: SportKey,
  teamKey: string,
  nextIds: { apiSportsTeamId?: string; espnTeamId?: string },
): Record<SportKey, Record<string, { apiSportsTeamId?: string; espnTeamId?: string }>> {
  const normalizedKey = teamKey.trim().toUpperCase();
  if (!normalizedKey) {
    return current;
  }
  const existing = current[sport]?.[normalizedKey] ?? {};
  const merged = {
    apiSportsTeamId: nextIds.apiSportsTeamId ?? existing.apiSportsTeamId,
    espnTeamId: nextIds.espnTeamId ?? existing.espnTeamId,
  };
  return {
    ...current,
    [sport]: {
      ...current[sport],
      [normalizedKey]: merged,
    },
  };
}

export function shouldUseServerWatchlist(props: Pick<WidgetCommonProps, "viewerMode" | "authConfigured" | "dbConfigured">): boolean {
  return props.viewerMode === "signed_in" && props.authConfigured && props.dbConfigured;
}

function normalizeSportKey(input: unknown): SportKey {
  if (input === "mlb" || input === "nba" || input === "nfl") {
    return input;
  }
  return "nfl";
}

function normalizeViewMode(input: unknown): ViewMode {
  return input === "players" ? "players" : "teams";
}

function normalizeStringArray(value: unknown): string[] {
  if (!Array.isArray(value)) {
    return [];
  }

  return value
    .map((entry) => (typeof entry === "string" ? entry.trim().toUpperCase() : ""))
    .filter(Boolean);
}

function normalizeTeamWatchlist(input: unknown): TeamWatchlistBySport {
  const source = input && typeof input === "object" ? (input as Record<string, unknown>) : {};
  return {
    nfl: normalizeStringArray(source.nfl),
    mlb: normalizeStringArray(source.mlb),
    nba: normalizeStringArray(source.nba),
  };
}

function normalizeTeamWatchlistNames(input: unknown): TeamWatchlistNamesBySport {
  const source = input && typeof input === "object" ? (input as Record<string, unknown>) : {};
  const out: TeamWatchlistNamesBySport = {
    nfl: {},
    mlb: {},
    nba: {},
  };

  for (const sport of ["nfl", "mlb", "nba"] as const) {
    const item = source[sport];
    if (!item || typeof item !== "object") {
      continue;
    }

    for (const [key, value] of Object.entries(item as Record<string, unknown>)) {
      if (typeof value === "string" && key.trim()) {
        out[sport][key.trim().toUpperCase()] = value.trim();
      }
    }
  }

  return out;
}

function normalizeProviderId(input: unknown): string | undefined {
  if (typeof input !== "string") {
    return undefined;
  }
  const trimmed = input.trim();
  return trimmed.length > 0 ? trimmed : undefined;
}

function normalizeTeamProviderIds(input: unknown): TeamProviderIdsBySport {
  const source = input && typeof input === "object" ? (input as Record<string, unknown>) : {};
  const out: TeamProviderIdsBySport = {
    nfl: {},
    mlb: {},
    nba: {},
  };

  for (const sport of ["nfl", "mlb", "nba"] as const) {
    const byTeam = source[sport];
    if (!byTeam || typeof byTeam !== "object") {
      continue;
    }

    for (const [teamKey, rawIds] of Object.entries(byTeam as Record<string, unknown>)) {
      if (!teamKey || !rawIds || typeof rawIds !== "object") {
        continue;
      }
      const typed = rawIds as Record<string, unknown>;
      const apiSportsTeamId = normalizeProviderId(typed.apiSportsTeamId);
      const espnTeamId = normalizeProviderId(typed.espnTeamId);
      if (!apiSportsTeamId && !espnTeamId) {
        continue;
      }
      out[sport][teamKey.trim().toUpperCase()] = {
        apiSportsTeamId,
        espnTeamId,
      };
    }
  }

  return out;
}

function normalizePlayerWatchlist(input: unknown): PlayerWatchlistBySport {
  const source = input && typeof input === "object" ? (input as Record<string, unknown>) : {};

  const next: PlayerWatchlistBySport = {
    nfl: [],
    mlb: [],
    nba: [],
  };

  for (const sport of ["nfl", "mlb", "nba"] as const) {
    const rows = source[sport];
    if (!Array.isArray(rows)) {
      continue;
    }

    const parsedRows: PlayerSearchResultMin[] = [];
    for (const row of rows) {
      if (!row || typeof row !== "object") {
        continue;
      }

      const typed = row as Record<string, unknown>;
      const playerId = typeof typed.playerId === "string" ? typed.playerId : "";
      const fullName = typeof typed.fullName === "string" ? typed.fullName : "";
      if (!playerId || !fullName) {
        continue;
      }

      const parsed: PlayerSearchResultMin = {
        playerId,
        fullName,
      };
      if (typeof typed.teamName === "string") {
        parsed.teamName = typed.teamName;
      }
      if (typeof typed.position === "string") {
        parsed.position = typed.position;
      }
      if (typeof typed.headshot === "string") {
        parsed.headshot = typed.headshot;
      }
      parsedRows.push(parsed);
    }

    next[sport] = parsedRows;
  }

  return next;
}

function legacyTeamsFromConfig(config: Record<string, unknown>): string[] {
  const watchlist = config.watchlist;
  if (!watchlist || typeof watchlist !== "object") {
    return [];
  }
  const teams = (watchlist as Record<string, unknown>).teams;
  return normalizeStringArray(teams);
}

function to12h(value: string): string {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "-";
  return date.toLocaleString(undefined, { hour: "numeric", minute: "2-digit", hour12: true });
}

function sportLabel(sportKey: SportKey): string {
  return sportKey.toUpperCase();
}

function uniqueByPlayerId(items: PlayerSearchResultMin[]): PlayerSearchResultMin[] {
  return items.filter((item, index, all) => all.findIndex((row) => row.playerId === item.playerId) === index);
}

function compact(parts: Array<string | undefined>): string {
  const values = parts.filter(Boolean) as string[];
  return values.length > 0 ? values.join(" · ") : "—";
}

export function normalizeTeamSearchText(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^\w\s]|_/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function normalizePlayerSearchText(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^\w\s]|_/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

export function selectExactTeamResult(query: string, results: TeamSearchResult[]): TeamSearchResult | null {
  const normalizedQuery = normalizeTeamSearchText(query);
  if (!normalizedQuery) {
    return null;
  }

  return results.find((result) =>
    normalizeTeamSearchText(result.displayName) === normalizedQuery
    || result.teamKey.toLowerCase() === normalizedQuery,
  ) ?? null;
}

function teamSearchScore(query: string, result: TeamSearchResult): number {
  const normalizedQuery = normalizeTeamSearchText(query);
  const normalizedName = normalizeTeamSearchText(result.displayName);
  const normalizedKey = result.teamKey.trim().toLowerCase();
  let score = 0;

  if (normalizedKey === normalizedQuery) {
    score += 180;
  } else if (normalizedName === normalizedQuery) {
    score += 150;
  } else if (normalizedName.startsWith(normalizedQuery)) {
    score += 110;
  } else if (normalizedName.includes(normalizedQuery)) {
    score += 80;
  }

  if (result.apiSportsTeamId) score += 20;
  if (result.espnTeamId) score += 20;
  if (result.logo) score += 8;

  return score;
}

export function rankTeamSearchResults(query: string, results: TeamSearchResult[]): TeamSearchResult[] {
  const deduped = new Map<string, TeamSearchResult>();
  for (const row of results) {
    const dedupeKey = row.teamKey.trim().toUpperCase();
    if (!deduped.has(dedupeKey)) {
      deduped.set(dedupeKey, row);
    }
  }

  return Array.from(deduped.values()).sort((left, right) => {
    const scoreDiff = teamSearchScore(query, right) - teamSearchScore(query, left);
    if (scoreDiff !== 0) {
      return scoreDiff;
    }
    return left.displayName.localeCompare(right.displayName);
  });
}

function playerSearchScore(query: string, result: PlayerSearchResultMin): number {
  const normalizedQuery = normalizePlayerSearchText(query);
  const normalizedName = normalizePlayerSearchText(result.fullName);
  let score = 0;

  if (normalizedName === normalizedQuery) {
    score += 160;
  } else if (normalizedName.startsWith(normalizedQuery)) {
    score += 120;
  } else if (normalizedName.includes(normalizedQuery)) {
    score += 90;
  }

  if (result.teamName) score += 18;
  if (result.position) score += 14;
  if (result.headshot) score += 6;

  return score;
}

export function rankPlayerSearchResults(query: string, results: PlayerSearchResultMin[]): PlayerSearchResultMin[] {
  const deduped = new Map<string, PlayerSearchResultMin>();
  for (const row of results) {
    const dedupeKey = row.playerId.trim() || `${normalizePlayerSearchText(row.fullName)}:${(row.teamName ?? "").trim().toLowerCase()}`;
    if (!deduped.has(dedupeKey)) {
      deduped.set(dedupeKey, row);
    }
  }

  return Array.from(deduped.values()).sort((left, right) => {
    const scoreDiff = playerSearchScore(query, right) - playerSearchScore(query, left);
    if (scoreDiff !== 0) {
      return scoreDiff;
    }
    return left.fullName.localeCompare(right.fullName);
  });
}

const DIAGNOSTIC_MESSAGE_PATTERNS = [
  "no schedule rows found",
  "no games found",
  "lookup failed",
  "api-sports",
  "espn",
  "endpoint",
  "request",
  "syntaxerror",
  "failed to fetch",
];

export function sanitizeRuntimeMessage(raw: string | null | undefined, fallback: string): string {
  const text = (raw ?? "").trim();
  if (!text) {
    return fallback;
  }
  const lowered = text.toLowerCase();
  if (DIAGNOSTIC_MESSAGE_PATTERNS.some((pattern) => lowered.includes(pattern))) {
    return fallback;
  }
  return text;
}

function teamStatusLabel(status: TeamStatus | undefined): string {
  if (!status || !status.hasGameToday) {
    return "No game today";
  }

  const opponent = status.opponent
    ? status.homeAway === "home"
      ? `vs ${status.opponent}`
      : `at ${status.opponent}`
    : "vs TBD";
  const score = status.score ? `${status.score.team}-${status.score.opp}` : undefined;

  if (status.state === "in") {
    return compact([`LIVE ${opponent}`, score, status.displayClock]);
  }
  if (status.state === "pre") {
    return compact([`Today ${opponent}`, status.displayClock]);
  }
  return compact([`Final ${opponent}`, score]);
}

export function teamCardStatusLabel(status: TeamStatus | undefined, team: TeamAdvanced | undefined): string {
  if (status?.hasGameToday) {
    return teamStatusLabel(status);
  }
  if (team?.lastGame) {
    return `Last: ${lastGameLabel(team)}`;
  }
  if (team?.nextGame) {
    return `Next: ${nextGameLabel(team)}`;
  }
  return "No game today";
}

export function teamCardSecondaryLabel(status: TeamStatus | undefined, team: TeamAdvanced | undefined): string | null {
  if (status?.hasGameToday) {
    if (team?.lastGame) {
      return `Last: ${lastGameLabel(team)}`;
    }
    if (team?.nextGame) {
      return `Next: ${nextGameLabel(team)}`;
    }
    return null;
  }

  if (team?.lastGame && team?.nextGame) {
    return `Next: ${nextGameLabel(team)}`;
  }

  return null;
}

function teamLiveDetail(status: TeamStatus | undefined): string {
  if (!status || !status.hasGameToday) {
    return "No live game state.";
  }
  const score = status.score ? `${status.score.team}-${status.score.opp}` : undefined;
  return compact([status.state?.toUpperCase(), score, status.displayClock]);
}

function lastGameLabel(team: TeamAdvanced | undefined): string {
  if (!team?.lastGame) {
    return "Not in today's schedule";
  }
  return compact([
    team.lastGame.result,
    team.lastGame.vs ? `vs ${team.lastGame.vs}` : undefined,
    team.lastGame.score,
    team.lastGame.when,
  ]);
}

function nextGameLabel(team: TeamAdvanced | undefined): string {
  if (!team?.nextGame) {
    return "Not in today's schedule";
  }
  const prefix = team.nextGame.homeAway === "home" ? "vs" : "at";
  return compact([team.nextGame.when, `${prefix} ${team.nextGame.vs ?? "TBD"}`]);
}

export function playerInsightsSummary(insight: PlayerInsights | undefined): string | null {
  if (!insight) {
    return null;
  }
  return insight.season?.headline ?? insight.recent?.headline ?? null;
}

export function playerSearchSubtitleLine(
  player: PlayerSearchResultMin,
  sportKey: SportKey,
  opts?: { includeId?: boolean },
): string | null {
  const parts = [player.position, player.teamName].filter(Boolean) as string[];
  if (parts.length > 0) {
    return compact(parts);
  }
  if (opts?.includeId) {
    return compact([sportLabel(sportKey), `ID ${player.playerId}`]);
  }
  return null;
}

export function playerWatchlistRecentLine(insight: PlayerInsights | undefined): string {
  const line = insight?.recent?.games?.[0]?.line?.trim();
  return line ? `Last: ${line}` : "No game data available";
}

export function playerWatchlistPrimaryContextLine(insight: PlayerInsights | undefined): string | null {
  if (insight?.live?.hasGameToday) {
    return playerTeamLiveLabel(insight);
  }
  const recent = insight?.recent?.games?.[0]?.line?.trim();
  if (recent) {
    return `Recent: ${recent}`;
  }
  const status = insight?.injury?.status?.trim();
  if (status) {
    return `Status: ${status}`;
  }
  return null;
}

function playerTeamLiveLabel(insight: PlayerInsights | undefined): string {
  if (!insight?.live) {
    return "Live context unavailable";
  }
  if (!insight.live.hasGameToday) {
    return "No game today";
  }
  const opponent = insight.live.opponent
    ? insight.live.homeAway === "home"
      ? `vs ${insight.live.opponent}`
      : `at ${insight.live.opponent}`
    : "vs TBD";
  const score = insight.live.score ? `${insight.live.score.team}-${insight.live.score.opp}` : undefined;
  return compact([insight.live.state?.toUpperCase(), opponent, score, insight.live.displayClock]);
}

export default function WatchlistWidget(props: WidgetCommonProps) {
  const [legacyItems, setLegacyItems] = useState<WatchItem[]>([]);
  const [legacyError, setLegacyError] = useState<string | null>(null);
  const [legacyLoaded, setLegacyLoaded] = useState(false);

  const [viewMode, setViewMode] = useState<ViewMode>(normalizeViewMode(props.config.watchlistMode));
  const [sportKey, setSportKey] = useState<SportKey>(normalizeSportKey(props.config.watchlistSportKey));

  const [playerWatchlist, setPlayerWatchlist] = useState<PlayerWatchlistBySport>(normalizePlayerWatchlist(props.config.playerWatchlist));
  const [teamWatchlist, setTeamWatchlist] = useState<TeamWatchlistBySport>(normalizeTeamWatchlist(props.config.teamWatchlist));
  const [teamWatchlistNames, setTeamWatchlistNames] = useState<TeamWatchlistNamesBySport>(normalizeTeamWatchlistNames(props.config.teamWatchlistNames));
  const [teamProviderIds, setTeamProviderIds] = useState<TeamProviderIdsBySport>(normalizeTeamProviderIds(props.config.teamProviderIds));

  const [teamQuery, setTeamQuery] = useState("");
  const [teamResults, setTeamResults] = useState<TeamSearchResult[]>([]);
  const [isTeamSearching, setIsTeamSearching] = useState(false);
  const [teamActiveIndex, setTeamActiveIndex] = useState(-1);
  const [teamSearchHint, setTeamSearchHint] = useState<string | null>(null);
  const [teamError, setTeamError] = useState<string | null>(null);

  const [playerQuery, setPlayerQuery] = useState("");
  const [playerResults, setPlayerResults] = useState<PlayerSearchResultMin[]>([]);
  const [isPlayerSearching, setIsPlayerSearching] = useState(false);
  const [playerError, setPlayerError] = useState<string | null>(null);

  const [lastProfile, setLastProfile] = useState<PlayerProfile | null>(null);
  const [lastCallMeta, setLastCallMeta] = useState<WidgetMeta | null>(null);
  const [teamStatusMeta, setTeamStatusMeta] = useState<WidgetMeta | null>(null);
  const [statusByTeam, setStatusByTeam] = useState<Record<string, TeamStatus>>({});
  const [teamAdvancedByKey, setTeamAdvancedByKey] = useState<Record<string, TeamAdvanced>>({});
  const [isLoadingTeamStatus, setIsLoadingTeamStatus] = useState(false);
  const [playerInsightsById, setPlayerInsightsById] = useState<Record<string, PlayerInsights>>({});
  const [playerInsightsMeta, setPlayerInsightsMeta] = useState<WidgetMeta | null>(null);
  const [lastEndpoint, setLastEndpoint] = useState("");

  const useServer = shouldUseServerWatchlist(props);
  const migratedRef = useRef(false);
  const keyRepairRef = useRef(false);
  const lastTeamSearchReqKeyRef = useRef("");
  const teamSearchAbortRef = useRef<AbortController | null>(null);
  const lastStatusReqKeyRef = useRef("");
  const lastStatusFetchAtRef = useRef(0);
  const statusAbortRef = useRef<AbortController | null>(null);
  const teamProviderBackfillReqKeyRef = useRef("");
  const lastQuickProfileKeyRef = useRef("");
  const lastPlayerInsightsReqKeyRef = useRef("");
  const lastPlayerInsightsFetchAtRef = useRef(0);
  const playerInsightsAbortRef = useRef<AbortController | null>(null);
  const playerSearchCacheRef = useRef(new Map<string, PlayerSearchResultMin[]>());
  const teamSearchCacheRef = useRef(new Map<string, TeamSearchResult[]>());

  useEffect(() => {
    setViewMode(normalizeViewMode(props.config.watchlistMode));
    setSportKey(normalizeSportKey(props.config.watchlistSportKey));
    setPlayerWatchlist(normalizePlayerWatchlist(props.config.playerWatchlist));
    setTeamWatchlist(normalizeTeamWatchlist(props.config.teamWatchlist));
    setTeamWatchlistNames(normalizeTeamWatchlistNames(props.config.teamWatchlistNames));
    setTeamProviderIds(normalizeTeamProviderIds(props.config.teamProviderIds));
  }, [props.config]);

  const loadLegacy = useCallback(async (): Promise<WatchItem[]> => {
    if (!useServer) {
      return getGuestWatchlist().items;
    }

    const res = await fetch("/api/watchlist", { cache: "no-store" });
    const json = (await res.json()) as WatchlistResponse;
    if (!res.ok) {
      throw new Error(json.error ?? "Failed to load watchlist");
    }
    return json.items ?? [];
  }, [useServer]);

  useEffect(() => {
    let cancelled = false;

    void (async () => {
      try {
        const items = await loadLegacy();
        if (!cancelled) {
          setLegacyItems(items);
          setLegacyError(null);
          setLegacyLoaded(true);
        }
      } catch (error) {
        if (!cancelled) {
          setLegacyError(String(error));
          setLegacyLoaded(true);
        }
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [loadLegacy, props.refreshTick]);

  useEffect(() => {
    if (migratedRef.current) {
      return;
    }
    if (!legacyLoaded) {
      return;
    }

    const hasNewShape = Array.isArray((props.config.teamWatchlist as Record<string, unknown> | undefined)?.nfl)
      || Array.isArray((props.config.teamWatchlist as Record<string, unknown> | undefined)?.mlb)
      || Array.isArray((props.config.teamWatchlist as Record<string, unknown> | undefined)?.nba);

    if (hasNewShape) {
      migratedRef.current = true;
      return;
    }

    const legacyConfig = legacyTeamsFromConfig(props.config);
    const legacyServer = legacyItems.map((item) => item.teamKey.trim().toUpperCase());
    const nflKeys = Array.from(new Set([...legacyConfig, ...legacyServer])).filter(Boolean);

    const nflNames: Record<string, string> = {};
    for (const item of legacyItems) {
      nflNames[item.teamKey.trim().toUpperCase()] = item.teamName;
    }

    const nextTeams: TeamWatchlistBySport = {
      nfl: nflKeys,
      mlb: [],
      nba: [],
    };
    const nextNames: TeamWatchlistNamesBySport = {
      nfl: nflNames,
      mlb: {},
      nba: {},
    };
    const nextProviderIds: TeamProviderIdsBySport = {
      nfl: {},
      mlb: {},
      nba: {},
    };

    setTeamWatchlist(nextTeams);
    setTeamWatchlistNames(nextNames);
    setTeamProviderIds(nextProviderIds);
    migratedRef.current = true;

    void props.onPersist({
      config: {
        ...props.config,
        watchlistSportKey: "nfl",
        teamWatchlist: nextTeams,
        teamWatchlistNames: nextNames,
        teamProviderIds: nextProviderIds,
      },
    });
  }, [legacyItems, legacyLoaded, props]);

  const persistConfig = useCallback(async (next: {
    viewMode?: ViewMode;
    sportKey?: SportKey;
    playerWatchlist?: PlayerWatchlistBySport;
    teamWatchlist?: TeamWatchlistBySport;
    teamWatchlistNames?: TeamWatchlistNamesBySport;
    teamProviderIds?: TeamProviderIdsBySport;
  }) => {
    const nextConfig = {
      ...props.config,
      watchlistMode: next.viewMode ?? viewMode,
      watchlistSportKey: next.sportKey ?? sportKey,
      playerWatchlist: next.playerWatchlist ?? playerWatchlist,
      teamWatchlist: next.teamWatchlist ?? teamWatchlist,
      teamWatchlistNames: next.teamWatchlistNames ?? teamWatchlistNames,
      teamProviderIds: next.teamProviderIds ?? teamProviderIds,
    };

    await props.onPersist({ config: nextConfig });
  }, [playerWatchlist, props, sportKey, teamProviderIds, teamWatchlist, teamWatchlistNames, viewMode]);

  // One-time startup repair: find non-canonical team keys (e.g. "TBJ", "PP") that were generated
  // by the broken name-acronym fallback, search by stored display name, and rename in place.
  useEffect(() => {
    if (!legacyLoaded || !migratedRef.current) {
      return;
    }
    if (keyRepairRef.current) {
      return;
    }

    const sportsToCheck = (["mlb", "nba"] as const);
    const hasBadKeys = sportsToCheck.some((sport) =>
      (teamWatchlist[sport] ?? []).some((key) => !isCanonicalTeamKey(sport, key)),
    );

    if (!hasBadKeys) {
      keyRepairRef.current = true;
      return;
    }

    keyRepairRef.current = true;
    let cancelled = false;

    void (async () => {
      let changed = false;
      const nextTeams: TeamWatchlistBySport = {
        nfl: [...(teamWatchlist.nfl ?? [])],
        mlb: [...(teamWatchlist.mlb ?? [])],
        nba: [...(teamWatchlist.nba ?? [])],
      };
      const nextNames: TeamWatchlistNamesBySport = {
        nfl: { ...teamWatchlistNames.nfl },
        mlb: { ...teamWatchlistNames.mlb },
        nba: { ...teamWatchlistNames.nba },
      };
      const nextIds: TeamProviderIdsBySport = {
        nfl: { ...teamProviderIds.nfl },
        mlb: { ...teamProviderIds.mlb },
        nba: { ...teamProviderIds.nba },
      };

      for (const sport of sportsToCheck) {
        const badKeys = (teamWatchlist[sport] ?? []).filter((key) => !isCanonicalTeamKey(sport, key));
        for (const badKey of badKeys) {
          const storedName = teamWatchlistNames[sport][badKey] ?? "";
          const query = storedName.trim() || badKey;
          if (query.length < 2) {
            continue;
          }
          try {
            const url = `/api/teams/search?sport=${sport}&q=${encodeURIComponent(query)}&limit=4&dataMode=${props.dataMode}`;
            const res = await fetch(url, { cache: "no-store" });
            if (!res.ok || cancelled) {
              continue;
            }
            const json = (await res.json()) as TeamSearchEnvelope;
            const rows = json.data ?? [];
            const match =
              selectExactTeamResult(query, rows) ??
              rows.find((row) => isCanonicalTeamKey(sport, row.teamKey));
            if (!match) {
              continue;
            }
            const goodKey = match.teamKey.trim().toUpperCase();
            if (goodKey === badKey) {
              continue;
            }
            // Rename badKey → goodKey across all maps
            const idx = nextTeams[sport].indexOf(badKey);
            if (idx !== -1) {
              nextTeams[sport][idx] = goodKey;
            }
            nextNames[sport][goodKey] = nextNames[sport][badKey] ?? match.displayName;
            // eslint-disable-next-line @typescript-eslint/no-dynamic-delete
            delete nextNames[sport][badKey];
            const prevIds = nextIds[sport][badKey] ?? {};
            nextIds[sport][goodKey] = {
              apiSportsTeamId: match.apiSportsTeamId ?? prevIds.apiSportsTeamId,
              espnTeamId: match.espnTeamId ?? prevIds.espnTeamId,
            };
            // eslint-disable-next-line @typescript-eslint/no-dynamic-delete
            delete nextIds[sport][badKey];
            changed = true;
          } catch {
            // best-effort; keep the bad key rather than crashing
          }
        }
      }

      if (!cancelled && changed) {
        setTeamWatchlist(nextTeams);
        setTeamWatchlistNames(nextNames);
        setTeamProviderIds(nextIds);
        await persistConfig({
          teamWatchlist: nextTeams,
          teamWatchlistNames: nextNames,
          teamProviderIds: nextIds,
        });
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [legacyLoaded, teamWatchlist, teamWatchlistNames, teamProviderIds, persistConfig, props.dataMode]);

  const teamsForSport = useMemo(() => teamWatchlist[sportKey] ?? [], [sportKey, teamWatchlist]);
  const playersForSport = useMemo(() => playerWatchlist[sportKey] ?? [], [playerWatchlist, sportKey]);
  const trimmedTeamQuery = useMemo(() => teamQuery.trim(), [teamQuery]);
  const debouncedTeamQuery = useDebouncedValue(trimmedTeamQuery, 300);
  const trimmedPlayerQuery = useMemo(() => playerQuery.trim(), [playerQuery]);
  const debouncedPlayerQuery = useDebouncedValue(trimmedPlayerQuery, 250);
  const currentPlayerIds = useMemo(
    () => Array.from(new Set(playersForSport.map((player) => player.playerId.trim()).filter(Boolean))).sort(),
    [playersForSport],
  );
  const currentTeamKeys = useMemo(
    () => Array.from(new Set(teamsForSport.map((key) => key.trim().toUpperCase()).filter(Boolean))).sort(),
    [teamsForSport],
  );
  const currentTeamRefs = useMemo(
    () => currentTeamKeys.map((teamKey) => ({
      teamKey,
      teamName: teamWatchlistNames[sportKey][teamKey],
      apiSportsTeamId: teamProviderIds[sportKey][teamKey]?.apiSportsTeamId,
      espnTeamId: teamProviderIds[sportKey][teamKey]?.espnTeamId,
    })),
    [currentTeamKeys, sportKey, teamProviderIds, teamWatchlistNames],
  );
  const statusReqKey = useMemo(
    () => stableKey({
      sportKey,
      teamRefs: currentTeamRefs,
      mode: props.mode,
      dataMode: props.dataMode,
      refreshTick: props.refreshTick,
    }),
    [currentTeamRefs, props.dataMode, props.mode, props.refreshTick, sportKey],
  );
  const teamsModeActive = viewMode === "teams";
  const playersModeActive = viewMode === "players";
  const playerInsightsReqKey = useMemo(
    () => stableKey({
      sportKey,
      playerIds: currentPlayerIds,
      mode: props.mode,
      dataMode: props.dataMode,
      refreshTick: props.refreshTick,
    }),
    [currentPlayerIds, props.dataMode, props.mode, props.refreshTick, sportKey],
  );
  const teamSearchReqKey = useMemo(
    () => stableKey({
      sportKey,
      q: debouncedTeamQuery.toLowerCase(),
      dataMode: props.dataMode,
      refreshTick: props.refreshTick,
    }),
    [debouncedTeamQuery, props.dataMode, props.refreshTick, sportKey],
  );

  const refreshTeamStatuses = useCallback(async (): Promise<void> => {
    if (!teamsModeActive) {
      return;
    }

    if (currentTeamKeys.length === 0) {
      setStatusByTeam({});
      setTeamStatusMeta(null);
      setTeamAdvancedByKey({});
      lastStatusReqKeyRef.current = "";
      lastStatusFetchAtRef.current = 0;
      return;
    }

    const now = Date.now();
    const keyChanged = statusReqKey !== lastStatusReqKeyRef.current;
    const stale = now - lastStatusFetchAtRef.current >= TEAM_STATUS_REFRESH_MS;
    if (!keyChanged && !stale) {
      return;
    }

    statusAbortRef.current?.abort();
    const controller = new AbortController();
    statusAbortRef.current = controller;
    setIsLoadingTeamStatus(true);

    try {
      const modeParam = props.mode.toLowerCase();
      const teamRefsParam = encodeURIComponent(JSON.stringify(currentTeamRefs));
      const endpoint = `/api/teams/advanced?sport=${sportKey}&teamKeys=${encodeURIComponent(currentTeamKeys.join(","))}&teamRefs=${teamRefsParam}&mode=${modeParam}&dataMode=${props.dataMode}&cacheBust=${props.refreshTick}`;
      setLastEndpoint(endpoint);

      const res = await fetch(endpoint, { cache: "no-store", signal: controller.signal });
      const json = (await res.json()) as TeamsAdvancedEnvelope;
      if (controller.signal.aborted) {
        return;
      }
      if (!res.ok || json.error || !json.data) {
        throw new Error(json.error?.message ?? "Failed to load team statuses");
      }

      const statusMap = json.data.teams.reduce<Record<string, TeamStatus>>((acc, team) => {
        acc[team.teamKey.toUpperCase()] = team.status;
        return acc;
      }, {});
      const advancedMap = json.data.teams.reduce<Record<string, TeamAdvanced>>((acc, team) => {
        acc[team.teamKey.toUpperCase()] = team;
        return acc;
      }, {});

      lastStatusReqKeyRef.current = statusReqKey;
      lastStatusFetchAtRef.current = Date.now();
      setStatusByTeam(statusMap);
      setTeamAdvancedByKey(advancedMap);
      setTeamStatusMeta(json.meta);
      setLastCallMeta(json.meta);
      setTeamError(null);
      setIsLoadingTeamStatus(false);
    } catch (error) {
      if (!controller.signal.aborted) {
        setIsLoadingTeamStatus(false);
        setTeamError(sanitizeRuntimeMessage(String(error), "Team status is temporarily unavailable."));
        setStatusByTeam({});
        setTeamAdvancedByKey({});
      }
    }
  }, [currentTeamKeys, currentTeamRefs, props.dataMode, props.mode, props.refreshTick, sportKey, statusReqKey, teamsModeActive]);

  useEffect(() => {
    if (!teamsModeActive) {
      statusAbortRef.current?.abort();
      return;
    }

    void refreshTeamStatuses();

    return () => {
      statusAbortRef.current?.abort();
    };
  }, [refreshTeamStatuses, statusReqKey, teamsModeActive]);

  useEffect(() => {
    if (!teamsModeActive || currentTeamKeys.length === 0) {
      return;
    }

    const intervalId = window.setInterval(() => {
      if (Date.now() - lastStatusFetchAtRef.current >= TEAM_STATUS_REFRESH_MS - 2000) {
        void refreshTeamStatuses();
      }
    }, TEAM_STATUS_REFRESH_MS);

    return () => {
      window.clearInterval(intervalId);
    };
  }, [currentTeamKeys.length, refreshTeamStatuses, statusReqKey, teamsModeActive]);

  const refreshPlayerInsights = useCallback(async (): Promise<void> => {
    if (!playersModeActive || props.mode !== "ADVANCED") {
      return;
    }

    if (currentPlayerIds.length === 0) {
      setPlayerInsightsById({});
      setPlayerInsightsMeta(null);
      lastPlayerInsightsReqKeyRef.current = "";
      lastPlayerInsightsFetchAtRef.current = 0;
      return;
    }

    const now = Date.now();
    const keyChanged = playerInsightsReqKey !== lastPlayerInsightsReqKeyRef.current;
    const stale = now - lastPlayerInsightsFetchAtRef.current >= PLAYER_INSIGHTS_REFRESH_MS;
    if (!keyChanged && !stale) {
      return;
    }

    playerInsightsAbortRef.current?.abort();
    const controller = new AbortController();
    playerInsightsAbortRef.current = controller;

    try {
      const endpoint = `/api/players/insights/batch?sport=${sportKey}&playerIds=${encodeURIComponent(currentPlayerIds.join(","))}&mode=advanced&dataMode=${props.dataMode}&cacheBust=${props.refreshTick}`;
      setLastEndpoint(endpoint);
      const response = await fetch(endpoint, { cache: "no-store", signal: controller.signal });
      const json = (await response.json()) as PlayerInsightsBatchEnvelope;
      if (controller.signal.aborted) {
        return;
      }
      if (!response.ok || json.error || !json.data) {
        throw new Error(json.error?.message ?? "Failed to load player insights");
      }

      const map = json.data.players.reduce<Record<string, PlayerInsights>>((acc, insight) => {
        acc[insight.playerId] = insight;
        return acc;
      }, {});

      lastPlayerInsightsReqKeyRef.current = playerInsightsReqKey;
      lastPlayerInsightsFetchAtRef.current = Date.now();
      setPlayerInsightsById(map);
      setPlayerInsightsMeta(json.meta);
      setLastCallMeta(json.meta);
    } catch (error) {
      if (!controller.signal.aborted) {
        setPlayerError(sanitizeRuntimeMessage(String(error), "Live context unavailable."));
      }
    }
  }, [currentPlayerIds, playerInsightsReqKey, playersModeActive, props.dataMode, props.mode, props.refreshTick, sportKey]);

  useEffect(() => {
    if (!playersModeActive || props.mode !== "ADVANCED") {
      playerInsightsAbortRef.current?.abort();
      setPlayerInsightsById({});
      setPlayerInsightsMeta(null);
      return;
    }

    void refreshPlayerInsights();
    return () => {
      playerInsightsAbortRef.current?.abort();
    };
  }, [playerInsightsReqKey, playersModeActive, props.mode, refreshPlayerInsights]);

  useEffect(() => {
    if (!playersModeActive || props.mode !== "ADVANCED" || currentPlayerIds.length === 0) {
      return;
    }

    const intervalId = window.setInterval(() => {
      if (Date.now() - lastPlayerInsightsFetchAtRef.current >= PLAYER_INSIGHTS_REFRESH_MS - 2000) {
        void refreshPlayerInsights();
      }
    }, PLAYER_INSIGHTS_REFRESH_MS);

    return () => {
      window.clearInterval(intervalId);
    };
  }, [currentPlayerIds.length, playersModeActive, props.mode, refreshPlayerInsights]);

  const runPlayerSearch = useCallback(async (value: string, signal: AbortSignal): Promise<PlayerSearchResultMin[]> => {
    if (value.trim().length < 3) {
      return [];
    }

    const cacheKey = stableKey({
      sportKey,
      q: value.trim().toLowerCase(),
      dataMode: props.dataMode,
      refreshTick: props.refreshTick,
    });
    const cached = playerSearchCacheRef.current.get(cacheKey);
    if (cached) {
      return cached;
    }

    const endpointUrl = `/api/players/search?sport=${sportKey}&q=${encodeURIComponent(value.trim())}&dataMode=${props.dataMode}&cacheBust=${props.refreshTick}`;
    setLastEndpoint(endpointUrl);

    const response = await fetch(endpointUrl, { cache: "no-store", signal });
    const json = (await response.json()) as Envelope<PlayerSearchResult[]>;

    if (!response.ok || json.error) {
      throw new Error(json.error?.message ?? "Player search failed.");
    }

    setLastCallMeta(json.meta);
    setPlayerError(null);

    const ranked = rankPlayerSearchResults(value, (json.data ?? []).map((row) => ({
      playerId: row.playerId,
      fullName: row.fullName,
      teamName: row.teamName,
      position: row.position,
      headshot: row.headshot,
    })));
    playerSearchCacheRef.current.set(cacheKey, ranked);
    if (playerSearchCacheRef.current.size > 50) {
      const firstKey = playerSearchCacheRef.current.keys().next().value;
      if (firstKey) {
        playerSearchCacheRef.current.delete(firstKey);
      }
    }
    return ranked;
  }, [props.dataMode, props.refreshTick, sportKey]);

  const runTeamSearch = useCallback(async (value: string, signal: AbortSignal): Promise<TeamSearchResult[]> => {
    if (value.trim().length < 2) {
      return [];
    }

    const cacheKey = stableKey({
      sportKey,
      q: value.trim().toLowerCase(),
      dataMode: props.dataMode,
      refreshTick: props.refreshTick,
    });
    const cached = teamSearchCacheRef.current.get(cacheKey);
    if (cached) {
      return cached;
    }

    const endpointUrl = `/api/teams/search?sport=${sportKey}&q=${encodeURIComponent(value.trim())}&limit=8&dataMode=${props.dataMode}&cacheBust=${props.refreshTick}`;
    setLastEndpoint(endpointUrl);

    const response = await fetch(endpointUrl, { cache: "no-store", signal });
    const json = (await response.json()) as TeamSearchEnvelope;

    if (!response.ok || json.error) {
      throw new Error(json.error?.message ?? "Team search failed.");
    }

    setLastCallMeta(json.meta);
    setTeamError(null);
    const ranked = rankTeamSearchResults(value, json.data ?? []);
    teamSearchCacheRef.current.set(cacheKey, ranked);
    if (teamSearchCacheRef.current.size > 50) {
      const firstKey = teamSearchCacheRef.current.keys().next().value;
      if (firstKey) {
        teamSearchCacheRef.current.delete(firstKey);
      }
    }
    return ranked;
  }, [props.dataMode, props.refreshTick, sportKey]);

  useEffect(() => {
    if (!playersModeActive) {
      setPlayerResults([]);
      setIsPlayerSearching(false);
      return;
    }

    if (debouncedPlayerQuery.length < 3) {
      setPlayerResults([]);
      setIsPlayerSearching(false);
      return;
    }

    const controller = new AbortController();
    setIsPlayerSearching(true);
    void (async () => {
      try {
        const results = await runPlayerSearch(debouncedPlayerQuery, controller.signal);
        if (controller.signal.aborted) {
          return;
        }
        setPlayerResults(results);
      } catch (error) {
        if (!controller.signal.aborted) {
          setPlayerError(sanitizeRuntimeMessage(String(error), "Player search is temporarily unavailable."));
          setPlayerResults([]);
        }
      } finally {
        if (!controller.signal.aborted) {
          setIsPlayerSearching(false);
        }
      }
    })();

    return () => {
      controller.abort();
    };
  }, [debouncedPlayerQuery, playersModeActive, runPlayerSearch]);

  useEffect(() => {
    if (!teamsModeActive) {
      teamSearchAbortRef.current?.abort();
      lastTeamSearchReqKeyRef.current = "";
      setTeamResults([]);
      setTeamActiveIndex(-1);
      setIsTeamSearching(false);
      setTeamSearchHint(null);
      return;
    }

    if (debouncedTeamQuery.length < 2) {
      teamSearchAbortRef.current?.abort();
      setTeamResults([]);
      setTeamActiveIndex(-1);
      setIsTeamSearching(false);
      setTeamSearchHint(null);
      return;
    }

    if (teamSearchReqKey === lastTeamSearchReqKeyRef.current) {
      return;
    }

    lastTeamSearchReqKeyRef.current = teamSearchReqKey;
    teamSearchAbortRef.current?.abort();
    const controller = new AbortController();
    teamSearchAbortRef.current = controller;
    setIsTeamSearching(true);

    void (async () => {
      try {
        const results = await runTeamSearch(debouncedTeamQuery, controller.signal);
        if (controller.signal.aborted) {
          return;
        }
        setTeamResults(results);
        setTeamActiveIndex(-1);
      } catch (error) {
        if (!controller.signal.aborted) {
          setTeamError(sanitizeRuntimeMessage(String(error), "Team search is temporarily unavailable."));
          setTeamResults([]);
          setTeamActiveIndex(-1);
        }
      } finally {
        if (!controller.signal.aborted) {
          setIsTeamSearching(false);
        }
      }
    })();

    return () => {
      controller.abort();
    };
  }, [debouncedTeamQuery, runTeamSearch, teamSearchReqKey, teamsModeActive]);

  useEffect(() => {
    const missingTeamKeys = currentTeamKeys.filter((teamKey) => {
      const ids = teamProviderIds[sportKey][teamKey];
      return !ids?.apiSportsTeamId && !ids?.espnTeamId;
    });

    if (missingTeamKeys.length === 0) {
      teamProviderBackfillReqKeyRef.current = "";
      return;
    }

    const reqKey = stableKey({
      sportKey,
      missingTeamKeys,
      labels: missingTeamKeys.map((teamKey) => teamWatchlistNames[sportKey][teamKey] ?? teamKey),
      dataMode: props.dataMode,
      refreshTick: props.refreshTick,
    });
    if (reqKey === teamProviderBackfillReqKeyRef.current) {
      return;
    }
    teamProviderBackfillReqKeyRef.current = reqKey;

    let cancelled = false;

    void (async () => {
      const nextBySport: TeamProviderIdsBySport = {
        ...teamProviderIds,
        [sportKey]: {
          ...teamProviderIds[sportKey],
        },
      };
      let changed = false;

      for (const teamKey of missingTeamKeys) {
        const query = (teamWatchlistNames[sportKey][teamKey] ?? teamKey).trim();
        if (query.length < 2) {
          continue;
        }
        try {
          const endpointUrl = `/api/teams/search?sport=${sportKey}&q=${encodeURIComponent(query)}&limit=8&dataMode=${props.dataMode}&cacheBust=${props.refreshTick}`;
          const response = await fetch(endpointUrl, { cache: "no-store" });
          const json = (await response.json()) as TeamSearchEnvelope;
          if (!response.ok || json.error) {
            continue;
          }
          const rows = json.data ?? [];
          const selected = rows.find((row) => row.teamKey.trim().toUpperCase() === teamKey)
            ?? selectExactTeamResult(query, rows);
          if (!selected) {
            continue;
          }
          const existing = nextBySport[sportKey][teamKey] ?? {};
          const apiSportsTeamId = selected.apiSportsTeamId ?? existing.apiSportsTeamId;
          const espnTeamId = selected.espnTeamId ?? existing.espnTeamId;
          if (apiSportsTeamId === existing.apiSportsTeamId && espnTeamId === existing.espnTeamId) {
            continue;
          }
          nextBySport[sportKey][teamKey] = {
            apiSportsTeamId,
            espnTeamId,
          };
          changed = true;
        } catch {
          // best-effort backfill; keep existing values
        }
      }

      if (!cancelled && changed) {
        setTeamProviderIds(nextBySport);
        await persistConfig({ teamProviderIds: nextBySport });
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [
    currentTeamKeys,
    persistConfig,
    props.dataMode,
    props.refreshTick,
    sportKey,
    teamProviderIds,
    teamWatchlistNames,
  ]);

  const addTeamFromResult = useCallback(async (result: TeamSearchResult) => {
    setTeamError(null);
    setTeamSearchHint(null);

    const key = result.teamKey.trim().toUpperCase();
    if (!key) {
      setTeamError("Selected team is missing a team key.");
      return;
    }

    if (currentTeamKeys.includes(key)) {
      setTeamError("Team is already in this sport watchlist.");
      return;
    }

    if (currentTeamKeys.length >= TEAM_LIMIT) {
      setTeamError(`Limit reached: ${TEAM_LIMIT} teams per sport.`);
      return;
    }

    const nextTeams = addTeamToSportWatchlist(teamWatchlist, sportKey, key);
    const nextNames: TeamWatchlistNamesBySport = {
      ...teamWatchlistNames,
      [sportKey]: {
        ...teamWatchlistNames[sportKey],
        [key]: result.displayName || teamWatchlistNames[sportKey][key] || key,
      },
    };
    const nextProviderIds = upsertTeamProviderIds(teamProviderIds, sportKey, key, {
      apiSportsTeamId: result.apiSportsTeamId,
      espnTeamId: result.espnTeamId,
    });

    setTeamWatchlist(nextTeams);
    setTeamWatchlistNames(nextNames);
    setTeamProviderIds(nextProviderIds);
    setTeamQuery("");
    setTeamResults([]);
    setTeamActiveIndex(-1);
    setIsTeamSearching(false);

    await persistConfig({
      teamWatchlist: nextTeams,
      teamWatchlistNames: nextNames,
      teamProviderIds: nextProviderIds,
    });
  }, [currentTeamKeys, persistConfig, sportKey, teamProviderIds, teamWatchlist, teamWatchlistNames]);

  const removeTeam = async (teamKey: string) => {
    const key = teamKey.trim().toUpperCase();

    const nextTeams: TeamWatchlistBySport = {
      ...teamWatchlist,
      [sportKey]: teamsForSport.filter((item) => item !== key),
    };
    const nextNames: TeamWatchlistNamesBySport = {
      ...teamWatchlistNames,
      [sportKey]: { ...teamWatchlistNames[sportKey] },
    };
    const nextProviderIds: TeamProviderIdsBySport = {
      ...teamProviderIds,
      [sportKey]: { ...teamProviderIds[sportKey] },
    };
    delete nextNames[sportKey][key];
    delete nextProviderIds[sportKey][key];

    setTeamWatchlist(nextTeams);
    setTeamWatchlistNames(nextNames);
    setTeamProviderIds(nextProviderIds);
    await persistConfig({
      teamWatchlist: nextTeams,
      teamWatchlistNames: nextNames,
      teamProviderIds: nextProviderIds,
    });
  };

  const onTeamSearchKeyDown = (event: React.KeyboardEvent<HTMLInputElement>) => {
    if (event.key === "ArrowDown") {
      event.preventDefault();
      if (teamResults.length === 0) {
        return;
      }
      setTeamActiveIndex((current) => {
        const next = current + 1;
        return next >= teamResults.length ? 0 : next;
      });
      return;
    }

    if (event.key === "ArrowUp") {
      event.preventDefault();
      if (teamResults.length === 0) {
        return;
      }
      setTeamActiveIndex((current) => {
        if (current <= 0) {
          return teamResults.length - 1;
        }
        return current - 1;
      });
      return;
    }

    if (event.key === "Escape") {
      setTeamResults([]);
      setTeamActiveIndex(-1);
      return;
    }

    if (event.key !== "Enter") {
      return;
    }

    event.preventDefault();

    const active = teamActiveIndex >= 0 && teamActiveIndex < teamResults.length
      ? teamResults[teamActiveIndex]
      : null;
    const exact = selectExactTeamResult(teamQuery, teamResults);
    const chosen = exact ?? active;

    if (chosen) {
      void addTeamFromResult(chosen);
      return;
    }

    if (teamQuery.trim().length >= 2 && teamResults.length > 0) {
      setTeamSearchHint("Select a team from the list.");
    }
  };

  const addPlayer = async (player: PlayerSearchResultMin) => {
    setPlayerError(null);

    if (playersForSport.some((existing) => existing.playerId === player.playerId)) {
      setPlayerError("Player is already in this sport watchlist.");
      return;
    }

    if (playersForSport.length >= PLAYER_LIMIT) {
      setPlayerError(`Limit reached: ${PLAYER_LIMIT} players per sport.`);
      return;
    }

    const nextWatchlist: PlayerWatchlistBySport = {
      ...playerWatchlist,
      [sportKey]: uniqueByPlayerId([...playersForSport, player]),
    };

    setPlayerWatchlist(nextWatchlist);
    setPlayerResults([]);
    setPlayerQuery("");

    await persistConfig({ playerWatchlist: nextWatchlist });
  };

  const removePlayer = async (playerId: string) => {
    const nextWatchlist: PlayerWatchlistBySport = {
      ...playerWatchlist,
      [sportKey]: playersForSport.filter((row) => row.playerId !== playerId),
    };

    setPlayerWatchlist(nextWatchlist);
    if (lastProfile?.playerId === playerId) {
      setLastProfile(null);
      lastQuickProfileKeyRef.current = "";
    }

    await persistConfig({ playerWatchlist: nextWatchlist });
  };

  const loadPlayerProfile = async (playerId: string) => {
    const profileKey = `${sportKey}:${playerId}:${props.dataMode}`;
    if (profileKey === lastQuickProfileKeyRef.current) {
      return;
    }
    lastQuickProfileKeyRef.current = profileKey;

    const endpointUrl = `/api/players/profile?sport=${sportKey}&playerId=${encodeURIComponent(playerId)}&dataMode=${props.dataMode}&cacheBust=${props.refreshTick}`;
    setLastEndpoint(endpointUrl);

    const response = await fetch(endpointUrl, { cache: "no-store" });
    const json = (await response.json()) as Envelope<PlayerProfile>;
    if (!response.ok || json.error) {
      setPlayerError("Player profile is temporarily unavailable.");
      return;
    }

    setLastCallMeta(json.meta);
    setPlayerError(null);
    setLastProfile(json.data ?? null);
  };

  const onViewModeChange = async (next: ViewMode) => {
    setViewMode(next);
    setTeamError(null);
    setPlayerError(null);
    if (next === "teams") {
      setIsPlayerSearching(false);
      setPlayerInsightsById({});
      setPlayerInsightsMeta(null);
      lastPlayerInsightsReqKeyRef.current = "";
    } else {
      setIsPlayerSearching(false);
      setTeamResults([]);
      setTeamQuery("");
      setTeamActiveIndex(-1);
      setTeamSearchHint(null);
      setIsTeamSearching(false);
      lastTeamSearchReqKeyRef.current = "";
    }
    await persistConfig({ viewMode: next });
  };

  const onSportChange = async (nextSportKey: SportKey) => {
    setSportKey(nextSportKey);
    setPlayerResults([]);
    setIsPlayerSearching(false);
    setPlayerQuery("");
    setTeamError(null);
    setPlayerError(null);
    setLastProfile(null);
    setTeamQuery("");
    setTeamResults([]);
    setTeamActiveIndex(-1);
    setTeamSearchHint(null);
    setIsTeamSearching(false);
    lastTeamSearchReqKeyRef.current = "";
    lastQuickProfileKeyRef.current = "";
    setPlayerInsightsById({});
    setPlayerInsightsMeta(null);
    setTeamAdvancedByKey({});
    lastPlayerInsightsReqKeyRef.current = "";
    lastStatusReqKeyRef.current = "";
    teamProviderBackfillReqKeyRef.current = "";
    await persistConfig({ sportKey: nextSportKey });
  };

  const headerMeta = viewMode === "teams"
    ? teamStatusMeta
    : (props.mode === "ADVANCED" ? (playerInsightsMeta ?? lastCallMeta) : lastCallMeta);

  return (
    <div className="space-y-2 text-xs">
      <div className="flex items-start justify-between gap-2">
        <span className="font-medium">Watchlist</span>
        <select
          className="rounded border border-neutral-700 bg-neutral-950 px-2 py-1"
          value={props.mode}
          onChange={(event) => props.onPersist({ mode: event.target.value as "BEGINNER" | "ADVANCED" })}
          disabled={props.locked}
        >
          <option value="BEGINNER">Beginner</option>
          <option value="ADVANCED">Advanced</option>
        </select>
      </div>

      <div className="space-y-1.5">
        <TabsRow
          items={MODE_TABS.map((item) => ({ key: item.key, label: item.label }))}
          value={viewMode}
          onChange={(key) => void onViewModeChange(key as ViewMode)}
          disabled={props.locked}
          size="sm"
        />

        <TabsRow
          items={SPORT_TABS.map((item) => ({ key: item.key, label: item.label }))}
          value={sportKey}
          onChange={(key) => void onSportChange(key as SportKey)}
          disabled={props.locked}
          size="sm"
        />
      </div>

      {viewMode === "teams" ? (
        <>
          <div className="space-y-2">
            <input
              className="w-full rounded border border-neutral-700 bg-neutral-950 px-2 py-1"
              placeholder={`Search ${sportLabel(sportKey)} teams (2+ chars)`}
              value={teamQuery}
              onKeyDown={onTeamSearchKeyDown}
              onChange={(event) => {
                setTeamQuery(event.target.value);
                setTeamSearchHint(null);
                setTeamResults([]);
                setTeamActiveIndex(-1);
                lastTeamSearchReqKeyRef.current = "";
              }}
              disabled={props.locked}
            />

            {trimmedTeamQuery.length < 2 ? <p className="text-neutral-400">Type 2+ chars to search teams.</p> : null}
            {isTeamSearching ? <p className="text-neutral-400">Searching teams...</p> : null}
            {teamSearchHint ? <p className="text-amber-300">{teamSearchHint}</p> : null}
            {debouncedTeamQuery.length >= 2 && !isTeamSearching && teamResults.length === 0 && !teamError ? <p className="text-neutral-400">No teams found.</p> : null}

            {teamResults.length > 0 ? (
              <div className="max-h-40 space-y-1 overflow-auto rounded border border-neutral-700 bg-neutral-950 p-1">
                {teamResults.map((result, index) => {
                  const isActive = index === teamActiveIndex;
                  const lowConfidence = !result.apiSportsTeamId && !result.espnTeamId && !result.logo;
                  return (
                    <button
                      key={`${sportKey}-team-search-${result.teamKey}-${result.displayName}`}
                      type="button"
                      className={`flex w-full items-center gap-2 rounded px-2 py-1 text-left ${isActive ? "bg-neutral-700 text-white" : "hover:bg-neutral-800"}`}
                      onMouseEnter={() => setTeamActiveIndex(index)}
                      onClick={() => void addTeamFromResult(result)}
                      disabled={props.locked}
                    >
                      {result.logo ? <img src={result.logo} alt={result.displayName} className="h-5 w-5 rounded object-contain" /> : null}
                      <span className="min-w-0">
                        <span className={`block truncate ${lowConfidence ? "text-neutral-300" : ""}`}>{result.displayName}</span>
                        <span className="block truncate text-[10px] text-neutral-400">{result.teamKey}</span>
                      </span>
                    </button>
                  );
                })}
              </div>
            ) : null}
          </div>

          <div className="flex items-center gap-1.5">
            <span className={`rounded px-1.5 py-0.5 text-[10px] font-medium ${currentTeamKeys.length >= TEAM_LIMIT ? "bg-amber-950 text-amber-400" : "bg-neutral-800 text-neutral-400"}`}>
              {currentTeamKeys.length}/{TEAM_LIMIT}
            </span>
            <span className="text-neutral-500">{sportLabel(sportKey)} teams</span>
          </div>

          {currentTeamKeys.map((key) => {
            const normalizedKey = key.toUpperCase();
            const label = teamWatchlistNames[sportKey][normalizedKey] ?? normalizedKey;
            const status = statusByTeam[normalizedKey];
            const advanced = teamAdvancedByKey[normalizedKey];
            const recordShort = advanced?.record
              ? `${advanced.record.wins}-${advanced.record.losses}${advanced.record.streak ? ` · ${advanced.record.streak}` : ""}`
              : null;
            const recordLabel = advanced?.record
              ? `${advanced.record.wins}-${advanced.record.losses}${advanced.record.pct ? ` (${advanced.record.pct})` : ""}${advanced.record.streak ? ` · ${advanced.record.streak}` : ""}${advanced.record.last10 ? ` · L10 ${advanced.record.last10}` : ""}`
              : null;
            const standingsLabel = advanced?.standings
              ? `${advanced.standings.conference ?? "Conference"} rank ${advanced.standings.rank ?? "-"}`
              : null;
            const lastLabel = lastGameLabel(advanced);
            const nextLabel = nextGameLabel(advanced);
            const secondaryLabel = teamCardSecondaryLabel(status, advanced);
            const hasScheduleData = Boolean(status?.hasGameToday || advanced?.lastGame || advanced?.nextGame);
            const hasAdvancedDetails = Boolean(recordLabel || standingsLabel || status?.hasGameToday || hasScheduleData);
            const statusText = teamCardStatusLabel(status, advanced);
            const isLive = status?.state === "in";
            const isToday = status?.hasGameToday && status?.state === "pre";
            return (
              <div key={`${sportKey}-team-${normalizedKey}`} className="rounded border border-neutral-800 bg-neutral-950 p-2.5">
                <div className="flex items-start justify-between gap-2">
                  <div className="min-w-0 flex-1">
                    <div className="flex flex-wrap items-center gap-1.5">
                      <span className="font-medium text-neutral-100">{label}</span>
                      <span className="rounded bg-neutral-800 px-1 py-0.5 text-[10px] text-neutral-400">{sportLabel(sportKey)}</span>
                      {recordShort ? (
                        <span className="rounded bg-neutral-800 px-1.5 py-0.5 text-[10px] font-medium text-neutral-300">{recordShort}</span>
                      ) : null}
                    </div>
                    <div className="mt-1">
                      {isLoadingTeamStatus && !statusByTeam[normalizedKey] && !teamAdvancedByKey[normalizedKey] ? (
                        <span className="rounded border border-neutral-800 bg-neutral-950 px-1.5 py-0.5 text-[10px] text-neutral-500">
                          Loading...
                        </span>
                      ) : (
                        <span className={`rounded border px-1.5 py-0.5 text-[10px] font-medium ${
                          isLive
                            ? "border-red-600 bg-red-950 text-red-300"
                            : isToday
                              ? "border-sky-600 bg-sky-950 text-sky-300"
                              : "border-neutral-700 bg-neutral-900 text-neutral-400"
                        }`}>
                          {statusText}
                        </span>
                      )}
                    </div>
                    {props.mode === "BEGINNER" ? (
                      secondaryLabel ? <p className="mt-1 text-neutral-500">{secondaryLabel}</p> : null
                    ) : (
                      <details className="mt-1.5 rounded border border-neutral-800 bg-black/20 p-2">
                        <summary className="cursor-pointer text-neutral-300">Details</summary>
                        <div className="mt-1.5 space-y-1 text-neutral-400">
                          <div className="flex justify-between gap-2"><span>Last</span><span>{lastLabel}</span></div>
                          <div className="flex justify-between gap-2"><span>Next</span><span>{nextLabel}</span></div>
                          {recordLabel ? <div className="flex justify-between gap-2"><span>Record</span><span>{recordLabel}</span></div> : null}
                          {standingsLabel ? <div className="flex justify-between gap-2"><span>Standings</span><span>{standingsLabel}</span></div> : null}
                          {status?.hasGameToday ? <div className="flex justify-between gap-2"><span>Live</span><span>{teamLiveDetail(status)}</span></div> : null}
                          {!hasScheduleData ? <p className="text-neutral-500">No game today · schedule data limited to current day.</p> : null}
                          {!hasAdvancedDetails ? <p className="text-neutral-500">No additional details available.</p> : null}
                        </div>
                      </details>
                    )}
                  </div>
                  <button
                    type="button"
                    onClick={() => void removeTeam(normalizedKey)}
                    disabled={props.locked}
                    className="shrink-0 rounded border border-neutral-700 px-2 py-0.5 text-neutral-400 hover:border-red-700 hover:text-red-400 disabled:opacity-40"
                  >
                    Remove
                  </button>
                </div>
              </div>
            );
          })}

          {currentTeamKeys.length === 0 ? <p className="text-neutral-500">No teams added for this sport yet.</p> : null}
          {teamError ? <p className="text-amber-300">{teamError}</p> : null}
          {legacyError ? <p className="text-amber-300">{legacyError}</p> : null}
        </>
      ) : (
        <>
          <input
            className="w-full rounded border border-neutral-700 bg-neutral-950 px-2 py-1"
            value={playerQuery}
            onChange={(event) => {
              setPlayerQuery(event.target.value);
              setPlayerResults([]);
            }}
            placeholder={`Search ${sportLabel(sportKey)} players (3+ chars)`}
            disabled={props.locked}
          />

          {trimmedPlayerQuery.length < 3 ? <p className="text-neutral-400">Type 3+ chars to search players.</p> : null}
          {isPlayerSearching ? <p className="text-neutral-400">Searching players...</p> : null}
          {debouncedPlayerQuery.length >= 3 && !isPlayerSearching && playerResults.length === 0 && !playerError ? <p className="text-neutral-400">No players found.</p> : null}

          {playerResults.length > 0 ? (
            <div className="max-h-40 space-y-1 overflow-auto rounded border border-neutral-700 bg-neutral-950 p-1">
              {playerResults.map((result) => {
                const subtitle = playerSearchSubtitleLine(result, sportKey, { includeId: props.mode === "ADVANCED" });
                const lowConfidence = !result.teamName && !result.position;
                return (
                  <div key={`${sportKey}-search-${result.playerId}`} className="flex items-center justify-between gap-2 rounded px-1 py-1 hover:bg-neutral-800">
                    <div className="flex min-w-0 items-center gap-2">
                      <img src={result.headshot || "/globe.svg"} alt="player" className="h-7 w-7 rounded object-cover" />
                      <div className="min-w-0">
                        <p className={`truncate font-medium ${lowConfidence ? "text-neutral-300" : ""}`}>{result.fullName}</p>
                        {subtitle ? <p className="truncate text-neutral-400">{subtitle}</p> : null}
                      </div>
                    </div>
                    <button type="button" className="rounded border border-neutral-700 px-2 py-0.5" onClick={() => void addPlayer(result)} disabled={props.locked}>Add</button>
                  </div>
                );
              })}
            </div>
          ) : null}

          <div className="flex items-center gap-1.5">
            <span className={`rounded px-1.5 py-0.5 text-[10px] font-medium ${playersForSport.length >= PLAYER_LIMIT ? "bg-amber-950 text-amber-400" : "bg-neutral-800 text-neutral-400"}`}>
              {playersForSport.length}/{PLAYER_LIMIT}
            </span>
            <span className="text-neutral-500">{sportLabel(sportKey)} players</span>
            {props.mode === "ADVANCED" && playersForSport.length > 0 && Object.keys(playerInsightsById).length === 0 ? (
              <span className="text-neutral-500">· Loading insights...</span>
            ) : null}
          </div>

          {playersForSport.length > 0 ? (
            <div className="space-y-1.5">
              {playersForSport.map((player) => {
                const insight = playerInsightsById[player.playerId];
                const insightSummary = playerInsightsSummary(insight);
                const primaryContext = playerWatchlistPrimaryContextLine(insight);
                const hasSeasonMetrics = Boolean(insight?.season?.metrics && insight.season.metrics.length > 0);
                const hasRecentGames = Boolean(insight?.recent?.games && insight.recent.games.length > 0);
                const hasAdvancedPlayerDetails = hasSeasonMetrics || hasRecentGames;
                const isPlayerLive = insight?.live?.state === "in";
                return (
                  <div key={`${sportKey}-watch-${player.playerId}`} className="rounded border border-neutral-800 bg-neutral-950 p-2">
                    <div className="flex items-start justify-between gap-2">
                      <button type="button" className="min-w-0 flex-1 text-left" onClick={() => void loadPlayerProfile(player.playerId)}>
                        <div className="flex items-start gap-2">
                          <img src={player.headshot || "/globe.svg"} alt="player" className="h-8 w-8 shrink-0 rounded object-cover" />
                          <div className="min-w-0">
                            <p className="truncate font-medium text-neutral-100">{player.fullName}</p>
                            <p className="truncate text-neutral-400">{compact([player.position, player.teamName, sportLabel(sportKey)])}</p>
                            {props.mode === "ADVANCED" && insightSummary ? (
                              <p className="truncate text-neutral-300">{insightSummary}</p>
                            ) : null}
                            {props.mode === "ADVANCED" && primaryContext ? (
                              <span className={`mt-0.5 inline-block rounded border px-1.5 py-0.5 text-[10px] font-medium ${
                                isPlayerLive
                                  ? "border-red-600 bg-red-950 text-red-300"
                                  : "border-neutral-700 bg-neutral-900 text-neutral-400"
                              }`}>
                                {primaryContext}
                              </span>
                            ) : null}
                          </div>
                        </div>
                      </button>
                      <button
                        type="button"
                        onClick={() => void removePlayer(player.playerId)}
                        disabled={props.locked}
                        className="shrink-0 rounded border border-neutral-700 px-2 py-0.5 text-neutral-400 hover:border-red-700 hover:text-red-400 disabled:opacity-40"
                      >
                        Remove
                      </button>
                    </div>

                    {props.mode === "ADVANCED" ? (
                      <details className="mt-1.5 rounded border border-neutral-800 bg-black/20 p-2">
                        <summary className="cursor-pointer text-neutral-300">Details</summary>
                        <div className="mt-1.5 space-y-1 text-neutral-400">
                          {hasSeasonMetrics ? (
                            <div className="grid grid-cols-1 gap-1 sm:grid-cols-2">
                              {(insight?.season?.metrics ?? []).slice(0, 4).map((metric) => (
                                <div key={`${player.playerId}-${metric.key}`} className="flex justify-between gap-1 truncate">
                                  <span className="text-neutral-500"><StatLabel label={metric.label} statKey={metric.key} sport={sportKey.toUpperCase()} mode={props.mode} /></span>
                                  <span className="text-neutral-300">{metric.value}</span>
                                </div>
                              ))}
                            </div>
                          ) : null}

                          {hasRecentGames ? (
                            <div className="space-y-1">
                              {(insight?.recent?.games ?? []).slice(0, 2).map((game, index) => (
                                <p key={`${player.playerId}-recent-${index}`} className="truncate">
                                  {game.date ?? "-"} · {game.opponent ?? "TBD"} · {game.line}
                                </p>
                              ))}
                            </div>
                          ) : null}

                          {!hasAdvancedPlayerDetails && !primaryContext ? <p className="text-neutral-500">No additional player detail available.</p> : null}
                        </div>
                      </details>
                    ) : null}
                  </div>
                );
              })}
            </div>
          ) : (
            <p className="text-neutral-500">No players added for this sport yet.</p>
          )}

          {lastProfile ? (
            <div className="rounded border border-neutral-700 bg-neutral-950 p-2">
              <p className="font-medium">{lastProfile.fullName}</p>
              <p>{compact([lastProfile.teamName, lastProfile.position, lastProfile.jersey ? `#${lastProfile.jersey}` : undefined])}</p>
              <p>{compact([lastProfile.height, lastProfile.weight, typeof lastProfile.age === "number" ? `Age ${lastProfile.age}` : undefined])}</p>
              <p className="text-[10px] text-neutral-500">
                Updated {lastCallMeta ? to12h(lastCallMeta.updatedAt) : "-"} · Source {lastCallMeta ? lastCallMeta.sourceUsed.toUpperCase() : "-"}
              </p>
            </div>
          ) : null}

          {playerError ? <p className="text-amber-300">{playerError}</p> : null}
        </>
      )}

      <div className="text-[10px] text-neutral-500">
        Updated {headerMeta ? to12h(headerMeta.updatedAt) : "-"} · Source {headerMeta ? headerMeta.sourceUsed.toUpperCase() : "-"}
      </div>

      {props.mode === "ADVANCED" ? (
        <details className="rounded border border-neutral-700 bg-black/20 p-2">
          <summary className="cursor-pointer text-[11px] text-neutral-300">Admin / Debug</summary>
          <p>View mode: {viewMode}</p>
          <p>Sport: {sportKey.toUpperCase()}</p>
          <p>Endpoint: {lastEndpoint || "-"}</p>
          <p>Request ID: {headerMeta?.requestId ?? "-"}</p>
          <pre className="overflow-auto text-[10px]">{JSON.stringify({
            teamWatchlist,
            teamWatchlistNames,
            teamProviderIds,
            playerWatchlist,
            teamAdvancedByKey,
            playerInsightsById,
            lastProfile,
            headerMeta,
          }, null, 2)}</pre>
        </details>
      ) : null}

      <button
        type="button"
        className="text-[10px] text-neutral-400 underline"
        onClick={() => props.onReportBug({
          widgetId: props.widgetId,
          mode: viewMode,
          sportKey,
          legacyError,
          teamError,
          playerError,
          lastEndpoint,
          headerMeta,
          teamWatchlist,
          teamProviderIds,
          playerWatchlist,
        })}
      >
        Report a bug
      </button>
    </div>
  );
}
