export type WidgetSport = "NFL" | "NBA" | "MLB" | "UTILITIES";

export type WidgetDefinition = {
  key: string;
  name: string;
  description: string;
  sportCategory: WidgetSport;
  defaultSize: { w: number; h: number };
  allowedSizes?: Array<{ w: number; h: number }>;
  stability?: "stable" | "experimental" | "admin";
  audience?: "beginner" | "advanced" | "mixed";
};

const SM = { w: 1, h: 1 };
const MD = { w: 2, h: 1 };
const LG = { w: 2, h: 2 };

export const WIDGET_DEFINITIONS: WidgetDefinition[] = [
  {
    key: "tonights_slate",
    name: "Tonight's Slate",
    description: "Today-first slate with offseason-safe next-slate fallback.",
    sportCategory: "NFL",
    defaultSize: { w: 1, h: 1 },
    allowedSizes: [SM, MD],
    stability: "stable",
    audience: "mixed",
  },
  {
    key: "nfl_division_snapshot",
    name: "NFL Division Snapshot",
    description: "Division-by-division standings context with an honest offseason final-standings view.",
    sportCategory: "NFL",
    defaultSize: { w: 1, h: 1 },
    allowedSizes: [SM, MD],
    stability: "stable",
    audience: "mixed",
  },
  {
    key: "nfl_team_context_card",
    name: "NFL Team Context Card",
    description: "Next-game or most-recent-game context for a selected NFL team, with honest bye and offseason handling.",
    sportCategory: "NFL",
    defaultSize: { w: 1, h: 1 },
    allowedSizes: [SM, MD],
    stability: "stable",
    audience: "mixed",
  },
  {
    key: "nfl_recent_form",
    name: "NFL Recent Form / Schedule Spot",
    description: "Recent-results board for a selected NFL team with schedule-difficulty flavor and explicit offseason honesty.",
    sportCategory: "NFL",
    defaultSize: { w: 1, h: 1 },
    allowedSizes: [SM, MD],
    stability: "stable",
    audience: "mixed",
  },
  {
    key: "player_card",
    name: "Player Card",
    description: "Player identity card with reliable profile fields and optional advanced insights.",
    sportCategory: "UTILITIES",
    defaultSize: { w: 1, h: 1 },
    allowedSizes: [SM, MD],
    stability: "stable",
    audience: "mixed",
  },
  {
    key: "watchlist",
    name: "Watchlist",
    description: "Track teams and players with prioritized live, recent, and next-game context.",
    sportCategory: "UTILITIES",
    defaultSize: { w: 1, h: 1 },
    allowedSizes: [SM, MD],
    stability: "stable",
    audience: "mixed",
  },
  {
    key: "rb_vs_dline",
    name: "RB vs D-Line",
    description: "Expected RB and run-defense matchup context.",
    sportCategory: "NFL",
    defaultSize: { w: 1, h: 1 },
    allowedSizes: [SM, MD, LG],
    stability: "experimental",
    audience: "advanced",
  },
  {
    key: "mlb_next_7_games",
    name: "MLB Next 7 Games",
    description: "Upcoming 7-game schedule for any MLB team via MLB Stats API.",
    sportCategory: "MLB",
    defaultSize: { w: 1, h: 1 },
    allowedSizes: [SM, MD],
    stability: "stable",
    audience: "mixed",
  },
  {
    key: "mlb_pitcher_arsenal",
    name: "Pitcher Arsenal",
    description: "Pitch-type breakdown with velocity and spin rate for a selected pitcher.",
    sportCategory: "MLB",
    defaultSize: { w: 1, h: 1 },
    allowedSizes: [SM, MD, LG],
    stability: "experimental",
    audience: "advanced",
  },
  {
    key: "mlb_series_tracker",
    name: "Series Tracker",
    description: "Current or upcoming series context with game-by-game results.",
    sportCategory: "MLB",
    defaultSize: { w: 1, h: 1 },
    allowedSizes: [SM, MD, LG],
    audience: "mixed",
  },
  {
    key: "mlb_starting_pitcher_matchup",
    name: "Starting Pitcher Matchup",
    description: "Probable starters with season stats for a team's next scheduled game.",
    sportCategory: "MLB",
    defaultSize: { w: 1, h: 1 },
    allowedSizes: [SM, MD, LG],
    stability: "stable",
    audience: "mixed",
  },
  {
    key: "mlb_season_stats",
    name: "Season Stats Explorer",
    description: "Year-by-year hitting or pitching stats for a player, or team stats for a season.",
    sportCategory: "MLB",
    defaultSize: { w: 1, h: 1 },
    allowedSizes: [SM, MD, LG],
  },
  {
    key: "mlb_platoon_advantage",
    name: "Platoon Advantage",
    description: "Analyzes pitcher platoon splits to identify home/away matchup advantages.",
    sportCategory: "MLB",
    defaultSize: { w: 1, h: 1 },
    allowedSizes: [SM, MD, LG],
  },
  {
    key: "mlb_recent_form",
    name: "Recent Form Rating",
    description: "Hot/Warm/Cool/Cold rating based on last 7, 14, and 30-day win percentages.",
    sportCategory: "MLB",
    defaultSize: { w: 1, h: 1 },
    allowedSizes: [SM, MD],
  },
  {
    key: "mlb_bullpen_fatigue",
    name: "Bullpen Fatigue Tracker",
    description: "Tracks active bullpen pitcher availability and fatigue based on recent appearances.",
    sportCategory: "MLB",
    defaultSize: { w: 1, h: 1 },
    allowedSizes: [SM, MD, LG],
  },
  {
    key: "mlb_run_expectancy",
    name: "Run Expectancy (RE24)",
    description: "Interactive RE24 matrix — click any base/out state to see expected runs and scoring probability.",
    sportCategory: "MLB",
    defaultSize: { w: 1, h: 1 },
    allowedSizes: [SM, MD, LG],
  },
  {
    key: "nba_tonights_slate",
    name: "NBA Tonight's Slate",
    description: "Today-first NBA slate using ESPN scoreboard data.",
    sportCategory: "NBA",
    defaultSize: { w: 1, h: 1 },
    allowedSizes: [SM, MD],
    stability: "stable",
    audience: "mixed",
  },
  {
    key: "nba_standings",
    name: "NBA Standings",
    description: "East/West standings snapshot with beginner/advanced depth.",
    sportCategory: "NBA",
    defaultSize: { w: 1, h: 1 },
    allowedSizes: [SM, MD],
    stability: "stable",
    audience: "mixed",
  },
  {
    key: "nba_team_matchup_profile",
    name: "NBA Team Matchup Profile",
    description: "Teachable matchup board with live team form when available, while deeper matchup pillars stay scaffolded until richer NBA split data is wired in.",
    sportCategory: "NBA",
    defaultSize: { w: 1, h: 1 },
    allowedSizes: [SM, MD, LG],
    stability: "experimental",
    audience: "mixed",
  },
  {
    key: "nba_rest_schedule_spot",
    name: "NBA Rest / Schedule Spot",
    description: "Rest edge and game-density context with live BALLDONTLIE schedule reads when a team key is selected, plus an honest demo fallback.",
    sportCategory: "NBA",
    defaultSize: { w: 1, h: 1 },
    allowedSizes: [SM, MD],
    stability: "experimental",
    audience: "mixed",
  },
  {
    key: "nba_player_role_form",
    name: "NBA Player Role + Form",
    description: "Role-based player context with live BALLDONTLIE player lookup and stat-backed form when available, plus an honest scaffold fallback.",
    sportCategory: "NBA",
    defaultSize: { w: 1, h: 1 },
    allowedSizes: [SM, MD, LG],
    stability: "experimental",
    audience: "mixed",
  },
  {
    key: "data_health",
    name: "Data Health",
    description: "Operational summary with optional provider diagnostics in advanced mode.",
    sportCategory: "UTILITIES",
    defaultSize: { w: 1, h: 1 },
    allowedSizes: [SM, MD],
    stability: "admin",
    audience: "advanced",
  },
  {
    key: "mlb_pitcher_projection",
    name: "MLB Pitcher Projection",
    description: "Projected strikeout total for a starting pitcher using season stats, recent form, market odds, and weather.",
    sportCategory: "MLB",
    defaultSize: { w: 1, h: 1 },
    allowedSizes: [SM, MD, LG],
    stability: "experimental",
    audience: "mixed",
  },
];
